{
  "hash": "8c7159c9e27c5ccb6c20230e564cdc85",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"FinTech Product Pitch: StepStone\"\ndescription: \"Conceptualising a FinTech app for Irish students and supporting it with econometric analysis and forecasting.\"\nimage: ../../assets/images/stepstone-logo.png\ncategories: [Python, Econometrics, FinTech, Data Analysis]\n---\n\n## Overview\n\nThis project was completed as part of the ECO1012 Econometrics and Forecasting module at DCU. The assignment challenged students to conceptualise a financial advisory FinTech product and support its launch with data analytics.\n\nI developed **StepStone**, a concept for a mobile app designed to help Irish university students progress toward long-term financial goals, such as buying their first home or building an investment portfolio. The project was built around a survey dataset of over 1,000 Irish university students, capturing demographics, employment, income, spending behaviour, and savings.\n\nThe data analysis, conducted in Python, covered the full analytical pipeline: data cleaning and validation, MCAR testing for missing data, outlier inspection, exploratory data analysis comparing students living at home versus independently, regression modelling, and forecasting. The project was accompanied by a video pitch presenting the product idea and key findings from the analysis.\n\nThis project developed my skills in econometric analysis, Python programming, data-driven storytelling, and presenting technical findings to a non-technical audience through video.\n\n\n## Video Pitch\n\n{{< video https://youtu.be/g3ddmqbRaks >}}\n\n\n## Data Analysis (Python Notebook)\n\n## FinTech Product: *StepStone* - Helping Students Progress Toward Long-Term Financial Goals\n\n**Product concept**: An app that coaches Irish university students toward long-term financial goals such as buying their first home, buying their first investment property, building an investment portfolio, or even retiring early. In this analysis, I focus on the first-home scenario.\n\nThe app analyses a student's financial situation and financial behaviour, then shows them when they can achieve their goal under several different behavioural patterns. This is designed to motivate users to increase their effort toward their goals and reach them sooner.\n\n**Core hypothesis**: Students living with their parents enjoy a natural cost advantage through lower essential spending, which gives them stronger potential to save and achieve long-term financial goals sooner. However, many waste significant part of this surplus on discretionary spending. By improving financial literacy and giving students more structure, the app can reduce unnecessary spending, increase savings, and make them more financially successful in the future.\n\n**Analysis roadmap**:\n\n1. **Data Cleaning** - prepare the student spending survey for analysis\n2. **Exploratory Data Analysis** - understand spending, balances, and saving capacity across groups\n3. **Regression Analysis** - model what drives saving potential and discretionary spending, with focus on living situation\n4. **Time Series Forecasting** - forecast Irish house prices to estimate the path to homeownership\n5. **Business Case** - quantify how the app accelerates the path to a mortgage deposit\n\n\n## Section 2: Imports\n\n::: {#468ffda9 .cell execution_count=1}\n``` {.python .cell-code}\nfrom pathlib import Path\n\nimport numpy as np                                              # numerical operations (arrays, math)\nimport pandas as pd                                             # data manipulation and DataFrames\nimport statsmodels.api as sm                                    # OLS regression models\nimport statsmodels.tsa.api as smt                               # time series models (ARIMA, ARMA order selection)\nimport statsmodels.tsa.stattools as st                          # stationarity tests (ADF)\nfrom statsmodels.stats.diagnostic import het_white              # White's test for heteroskedasticity\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor  # VIF for multicollinearity\nfrom scipy.stats import ttest_ind, chi2_contingency             # t-tests and chi-square for MCAR testing\nimport matplotlib.pyplot as plt                                 # plotting and visualisation\nimport seaborn as sns                                           # statistical visualisation (heatmaps, boxplots)\nimport warnings                                                 # suppress convergence warnings in grid search\n\n\ndef resolve_data_path(filename):\n    candidates = [\n        Path(\"data\") / filename,\n        Path(\"../../data\") / filename,\n        Path(\n            r\"C:\\Users\\uzivatel\\OneDrive - Dublin City University\\ac_Workflow_data_management\\Projects\\Econometrics\\data\"\n        ) / filename,\n    ]\n    for candidate in candidates:\n        if candidate.exists():\n            return candidate\n    raise FileNotFoundError(f\"Could not find {filename}\")\n```\n:::\n\n\n## Section 3: Data Loading\n\nWe load the student spending survey dataset (1,026 responses). This is a cross-sectional survey of Irish university students capturing demographics, employment, income, living arrangements, parental support, spending behaviour, and current savings balances. Data has been mocked up using Claude Opus 4.6.\n\nThese variables allow us to study both the students' current financial position and their potential to make faster progress toward long-term goals such as homeownership.\n\n::: {#04cfd68d .cell execution_count=2}\n``` {.python .cell-code}\n# 3.1 — Load the raw survey data and inspect its structure\n# We check: number of rows/columns, data types (numeric vs categorical),\n# and preview the first rows to spot obvious issues (missing values, formatting).\ndf = pd.read_csv(resolve_data_path('student_spending_survey.csv'))\n\nprint(f\"Dataset shape: {df.shape[0]} rows x {df.shape[1]} columns\\n\")\nprint(\"Column types:\")\nprint(df.dtypes)\nprint(\"\\nColumns:\")\nprint(df.columns.tolist())\nprint(\"\\n--- First 5 rows ---\")\ndf.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataset shape: 1026 rows x 13 columns\n\nColumn types:\nstudent_id                     int64\nage                            int64\nsex                           object\nfield_of_study                object\nyear_of_study                  int64\nemployment_status             object\nincome_highest_month         float64\nincome_lowest_month          float64\nliving_with_parents           object\nfinancial_support_parents    float64\nessential_spending             int64\ndiscretionary_spending       float64\ncurrent_savings_balance        int64\ndtype: object\n\nColumns:\n['student_id', 'age', 'sex', 'field_of_study', 'year_of_study', 'employment_status', 'income_highest_month', 'income_lowest_month', 'living_with_parents', 'financial_support_parents', 'essential_spending', 'discretionary_spending', 'current_savings_balance']\n\n--- First 5 rows ---\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>student_id</th>\n      <th>age</th>\n      <th>sex</th>\n      <th>field_of_study</th>\n      <th>year_of_study</th>\n      <th>employment_status</th>\n      <th>income_highest_month</th>\n      <th>income_lowest_month</th>\n      <th>living_with_parents</th>\n      <th>financial_support_parents</th>\n      <th>essential_spending</th>\n      <th>discretionary_spending</th>\n      <th>current_savings_balance</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>429</td>\n      <td>20</td>\n      <td>Female</td>\n      <td>Health Sciences</td>\n      <td>2</td>\n      <td>Unemployed</td>\n      <td>NaN</td>\n      <td>0.0</td>\n      <td>Yes</td>\n      <td>0.0</td>\n      <td>270</td>\n      <td>80.0</td>\n      <td>75</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>533</td>\n      <td>22</td>\n      <td>Female</td>\n      <td>business</td>\n      <td>4</td>\n      <td>Part-time</td>\n      <td>870.0</td>\n      <td>440.0</td>\n      <td>No</td>\n      <td>650.0</td>\n      <td>680</td>\n      <td>170.0</td>\n      <td>26500</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>389</td>\n      <td>20</td>\n      <td>Female</td>\n      <td>Business</td>\n      <td>3</td>\n      <td>Freelance</td>\n      <td>2190.0</td>\n      <td>300.0</td>\n      <td>Yes</td>\n      <td>0.0</td>\n      <td>240</td>\n      <td>350.0</td>\n      <td>8100</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>108</td>\n      <td>21</td>\n      <td>Male</td>\n      <td>STEM</td>\n      <td>3</td>\n      <td>Unemployed</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>Yes</td>\n      <td>0.0</td>\n      <td>280</td>\n      <td>50.0</td>\n      <td>175</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>424</td>\n      <td>20</td>\n      <td>Male</td>\n      <td>Social Sciences</td>\n      <td>2</td>\n      <td>Part-time</td>\n      <td>1030.0</td>\n      <td>530.0</td>\n      <td>No</td>\n      <td>50.0</td>\n      <td>580</td>\n      <td>190.0</td>\n      <td>1275</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Section 4: Data Cleaning\n\nBefore any analysis, we need to address data quality issues common in survey data:\n\n1. **Missing values** — some respondents left fields blank\n2. **Inconsistent labels** — typos and case variations in categorical fields\n3. **Duplicate entries** — repeated submissions\n4. **Outliers** — data points unusually far from the rest \n\nWe will systematically identify each issue, assess whether missing data is random (MCAR test), and then clean the dataset.\n\n::: {#2030cca6 .cell execution_count=3}\n``` {.python .cell-code}\n# 4.1 — Check missing values per column\n# Identify which columns have gaps and how many rows are affected.\n# This informs whether we can safely drop incomplete rows (if few)\n# or need imputation (if many).\nprint(\"Missing values per column:\")\nprint(df.isnull().sum())\nprint(f\"\\nTotal missing values: {df.isnull().sum().sum()}\")\nprint(f\"Rows with at least one missing value: {df.isnull().any(axis=1).sum()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMissing values per column:\nstudent_id                    0\nage                           0\nsex                           0\nfield_of_study                0\nyear_of_study                 0\nemployment_status             0\nincome_highest_month         11\nincome_lowest_month          11\nliving_with_parents           0\nfinancial_support_parents    12\nessential_spending            0\ndiscretionary_spending       14\ncurrent_savings_balance       0\ndtype: int64\n\nTotal missing values: 48\nRows with at least one missing value: 47\n```\n:::\n:::\n\n\n::: {#48c97b3a .cell execution_count=4}\n``` {.python .cell-code}\n# 4.2 — Check field_of_study for inconsistent labels (typos, case issues)\n# Categorical variables must have clean, consistent labels before we can\n# create dummy variables for regression. Any typos or case mismatches\n# would create spurious categories.\nprint(\"Unique field_of_study values:\")\nprint(df['field_of_study'].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUnique field_of_study values:\nfield_of_study\nBusiness             267\nSTEM                 264\nArts & Humanities    218\nHealth Sciences      140\nSocial Sciences      131\nbusiness               1\nstem                   1\nBusines                1\nSocial Sciences        1\nHealth sciences        1\nArts & humanities      1\nName: count, dtype: int64\n```\n:::\n:::\n\n\n::: {#eed7680d .cell execution_count=5}\n``` {.python .cell-code}\n# 4.3 — Fix field_of_study: strip whitespace, map typos to standard labels\n# We see entries like \"business\", \"Busines\", \"stem\", \"Arts & humanities\",\n# \"Health sciences\", \"Social Sciences \" (trailing space).\n# These are clearly the same categories with typos or case differences.\n\ndf['field_of_study'] = df['field_of_study'].str.strip()  # remove leading/trailing whitespace\n\n# Map all known variations to their correct standard labels\nfield_mapping = {\n    'business': 'Business',\n    'Busines': 'Business',\n    'stem': 'STEM',\n    'Arts & humanities': 'Arts & Humanities',\n    'Health sciences': 'Health Sciences',\n}\ndf['field_of_study'] = df['field_of_study'].replace(field_mapping)\n\n# Verify fix — should show exactly 5 clean categories\nprint(\"After cleaning — unique field_of_study values:\")\nprint(df['field_of_study'].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAfter cleaning — unique field_of_study values:\nfield_of_study\nBusiness             269\nSTEM                 265\nArts & Humanities    219\nHealth Sciences      141\nSocial Sciences      132\nName: count, dtype: int64\n```\n:::\n:::\n\n\n### 4.4 - Financial Validity Checks\n\nBefore testing missingness, we verify that the raw survey finance variables satisfy basic logical constraints. In this dataset:\n\n- income variables should not be negative\n- financial support should not be negative\n- spending variables should not be negative\n- current savings balance should not be negative\n- `income_lowest_month` should be less than or equal to `income_highest_month` for each student\n\nThese are essential validity checks because financial variables can vary widely across students, but they must still remain economically possible.\n\n::: {#bf2836bb .cell execution_count=6}\n``` {.python .cell-code}\n# 4.4 - Check for impossible financial values\nvalidity_checks = {\n    'Negative values in income_highest_month': int((df['income_highest_month'].dropna() < 0).sum()),\n    'Negative values in income_lowest_month': int((df['income_lowest_month'].dropna() < 0).sum()),\n    'Negative values in financial_support_parents': int((df['financial_support_parents'].dropna() < 0).sum()),\n    'Negative values in essential_spending': int((df['essential_spending'].dropna() < 0).sum()),\n    'Negative values in discretionary_spending': int((df['discretionary_spending'].dropna() < 0).sum()),\n    'Negative values in current_savings_balance': int((df['current_savings_balance'].dropna() < 0).sum()),\n    'income_lowest_month > income_highest_month': int(((df['income_lowest_month'].notna())\n                                                  & (df['income_highest_month'].notna())\n                                                  & (df['income_lowest_month'] > df['income_highest_month'])).sum())\n}\n\nprint('Financial validity checks:\\n')\nfor check, count in validity_checks.items():\n    print(f'{check}: {count}')\n\nprint('\\nInterpretation: zero violations means the raw financial variables satisfy the key logical constraints.')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFinancial validity checks:\n\nNegative values in income_highest_month: 0\nNegative values in income_lowest_month: 0\nNegative values in financial_support_parents: 0\nNegative values in essential_spending: 0\nNegative values in discretionary_spending: 0\nNegative values in current_savings_balance: 0\nincome_lowest_month > income_highest_month: 0\n\nInterpretation: zero violations means the raw financial variables satisfy the key logical constraints.\n```\n:::\n:::\n\n\n### 4.5 - MCAR Test (Missing Completely At Random)\n\nBefore dropping rows with missing values, we must check whether the missingness is **random** or **systematic**. If data is Missing Completely At Random (MCAR), then listwise deletion (dropping incomplete rows) does not introduce bias.\n\n**Method**: For each column with missing values, we create a binary indicator (1 = missing, 0 = observed). Then:\n\n- **t-tests**: compare means of numeric variables between the missing and non-missing groups\n- **Chi-square tests**: test whether missingness is associated with categorical variables\n\nIf all p-values are above 0.05, we conclude there is no systematic pattern and listwise deletion is appropriate.\n\n::: {#bc1857cd .cell execution_count=7}\n``` {.python .cell-code}\n# 4.5 - MCAR testing: check if missingness is random\n# Columns with missing values\ncols_with_na = df.columns[df.isnull().any()].tolist()\nprint(f\"Columns with missing values: {cols_with_na}\\n\")\n\n# Numeric columns to compare (excluding the ones being tested for missingness)\nnumeric_cols = ['age', 'year_of_study', 'essential_spending', 'current_savings_balance']\n# Categorical columns to test association with\ncat_cols = ['sex', 'employment_status', 'living_with_parents', 'field_of_study']\n\nresults = []\n\nfor col in cols_with_na:\n    missing_indicator = df[col].isnull()\n\n    for num_col in numeric_cols:\n        group_missing = df.loc[missing_indicator, num_col].dropna()\n        group_observed = df.loc[~missing_indicator, num_col].dropna()\n        if len(group_missing) >= 2 and len(group_observed) >= 2:\n            t_stat, p_val = ttest_ind(group_missing, group_observed)\n            results.append({\n                'missing_col': col,\n                'test_var': num_col,\n                'test': 't-test',\n                'statistic': round(t_stat, 3),\n                'p_value': round(p_val, 4)\n            })\n\n    for cat_col in cat_cols:\n        contingency = pd.crosstab(missing_indicator, df[cat_col])\n        if contingency.shape[0] == 2 and contingency.shape[1] >= 2:\n            chi2, p_val, dof, expected = chi2_contingency(contingency)\n            results.append({\n                'missing_col': col,\n                'test_var': cat_col,\n                'test': 'chi-square',\n                'statistic': round(chi2, 3),\n                'p_value': round(p_val, 4)\n            })\n\nresults_df = pd.DataFrame(results)\nprint(f\"Total tests conducted: {len(results_df)}\")\nprint(f\"Tests with p < 0.05 (significant): {(results_df['p_value'] < 0.05).sum()}\\n\")\nresults_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nColumns with missing values: ['income_highest_month', 'income_lowest_month', 'financial_support_parents', 'discretionary_spending']\n\nTotal tests conducted: 32\nTests with p < 0.05 (significant): 1\n\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>missing_col</th>\n      <th>test_var</th>\n      <th>test</th>\n      <th>statistic</th>\n      <th>p_value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>income_highest_month</td>\n      <td>age</td>\n      <td>t-test</td>\n      <td>0.598</td>\n      <td>0.5501</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>income_highest_month</td>\n      <td>year_of_study</td>\n      <td>t-test</td>\n      <td>0.612</td>\n      <td>0.5406</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>income_highest_month</td>\n      <td>essential_spending</td>\n      <td>t-test</td>\n      <td>-0.445</td>\n      <td>0.6564</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>income_highest_month</td>\n      <td>current_savings_balance</td>\n      <td>t-test</td>\n      <td>0.707</td>\n      <td>0.4799</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>income_highest_month</td>\n      <td>sex</td>\n      <td>chi-square</td>\n      <td>0.477</td>\n      <td>0.4896</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>income_highest_month</td>\n      <td>employment_status</td>\n      <td>chi-square</td>\n      <td>0.895</td>\n      <td>0.8267</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>income_highest_month</td>\n      <td>living_with_parents</td>\n      <td>chi-square</td>\n      <td>0.000</td>\n      <td>1.0000</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>income_highest_month</td>\n      <td>field_of_study</td>\n      <td>chi-square</td>\n      <td>4.234</td>\n      <td>0.3752</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>income_lowest_month</td>\n      <td>age</td>\n      <td>t-test</td>\n      <td>-0.859</td>\n      <td>0.3904</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>income_lowest_month</td>\n      <td>year_of_study</td>\n      <td>t-test</td>\n      <td>-2.404</td>\n      <td>0.0164</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>income_lowest_month</td>\n      <td>essential_spending</td>\n      <td>t-test</td>\n      <td>-0.913</td>\n      <td>0.3612</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>income_lowest_month</td>\n      <td>current_savings_balance</td>\n      <td>t-test</td>\n      <td>-0.627</td>\n      <td>0.5309</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>income_lowest_month</td>\n      <td>sex</td>\n      <td>chi-square</td>\n      <td>0.272</td>\n      <td>0.6017</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>income_lowest_month</td>\n      <td>employment_status</td>\n      <td>chi-square</td>\n      <td>4.944</td>\n      <td>0.1760</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>income_lowest_month</td>\n      <td>living_with_parents</td>\n      <td>chi-square</td>\n      <td>0.000</td>\n      <td>0.9880</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>income_lowest_month</td>\n      <td>field_of_study</td>\n      <td>chi-square</td>\n      <td>2.764</td>\n      <td>0.5980</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>financial_support_parents</td>\n      <td>age</td>\n      <td>t-test</td>\n      <td>-1.053</td>\n      <td>0.2925</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>financial_support_parents</td>\n      <td>year_of_study</td>\n      <td>t-test</td>\n      <td>0.497</td>\n      <td>0.6195</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>financial_support_parents</td>\n      <td>essential_spending</td>\n      <td>t-test</td>\n      <td>0.807</td>\n      <td>0.4197</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>financial_support_parents</td>\n      <td>current_savings_balance</td>\n      <td>t-test</td>\n      <td>-0.965</td>\n      <td>0.3346</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>financial_support_parents</td>\n      <td>sex</td>\n      <td>chi-square</td>\n      <td>0.041</td>\n      <td>0.8398</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>financial_support_parents</td>\n      <td>employment_status</td>\n      <td>chi-square</td>\n      <td>4.631</td>\n      <td>0.2009</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>financial_support_parents</td>\n      <td>living_with_parents</td>\n      <td>chi-square</td>\n      <td>0.066</td>\n      <td>0.7971</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>financial_support_parents</td>\n      <td>field_of_study</td>\n      <td>chi-square</td>\n      <td>1.513</td>\n      <td>0.8244</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>discretionary_spending</td>\n      <td>age</td>\n      <td>t-test</td>\n      <td>0.323</td>\n      <td>0.7470</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>discretionary_spending</td>\n      <td>year_of_study</td>\n      <td>t-test</td>\n      <td>1.510</td>\n      <td>0.1313</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>discretionary_spending</td>\n      <td>essential_spending</td>\n      <td>t-test</td>\n      <td>-0.538</td>\n      <td>0.5905</td>\n    </tr>\n    <tr>\n      <th>27</th>\n      <td>discretionary_spending</td>\n      <td>current_savings_balance</td>\n      <td>t-test</td>\n      <td>-0.738</td>\n      <td>0.4607</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>discretionary_spending</td>\n      <td>sex</td>\n      <td>chi-square</td>\n      <td>0.030</td>\n      <td>0.8621</td>\n    </tr>\n    <tr>\n      <th>29</th>\n      <td>discretionary_spending</td>\n      <td>employment_status</td>\n      <td>chi-square</td>\n      <td>0.960</td>\n      <td>0.8109</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>discretionary_spending</td>\n      <td>living_with_parents</td>\n      <td>chi-square</td>\n      <td>0.165</td>\n      <td>0.6850</td>\n    </tr>\n    <tr>\n      <th>31</th>\n      <td>discretionary_spending</td>\n      <td>field_of_study</td>\n      <td>chi-square</td>\n      <td>1.574</td>\n      <td>0.8134</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n**MCAR Interpretation**: Out of 32 tests, only 1 shows a p-value below 0.05. With 32 tests conducted at the 5% significance level, we would expect around 1-2 false positives by chance alone (32 x 0.05 = 1.6). A single significant result does not suggest a systematic missingness pattern.\n\nThe evidence is therefore broadly consistent with the data being **Missing Completely At Random (MCAR)**, which means listwise deletion (dropping rows with any missing value) is a reasonable and defensible approach for this analysis.\n\n::: {#7b55207c .cell execution_count=8}\n``` {.python .cell-code}\n# 4.6 - Drop rows with missing values (justified by MCAR evidence above)\nprint(f\"Shape before dropping NaN: {df.shape}\")\ndf = df.dropna()\nprint(f\"Shape after dropping NaN:  {df.shape}\")\nprint(f\"Remaining missing values:  {df.isnull().sum().sum()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nShape before dropping NaN: (1026, 13)\nShape after dropping NaN:  (979, 13)\nRemaining missing values:  0\n```\n:::\n:::\n\n\n::: {#65d1fab8 .cell execution_count=9}\n``` {.python .cell-code}\n# 4.7 - Remove duplicate rows\nprint(f\"Duplicate rows found: {df.duplicated().sum()}\")\ndf = df.drop_duplicates()\ndf = df.reset_index(drop=True)\nprint(f\"Shape after removing duplicates: {df.shape}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDuplicate rows found: 2\nShape after removing duplicates: (977, 13)\n```\n:::\n:::\n\n\n::: {#4a59748d .cell execution_count=10}\n``` {.python .cell-code}\n# 4.8 - Verify clean state\nprint(f\"Final shape: {df.shape}\")\nprint(f\"Missing values: {df.isnull().sum().sum()}\")\nprint(f\"Duplicates: {df.duplicated().sum()}\")\nprint(f\"Unique field_of_study: {df['field_of_study'].unique()}\")\nprint(f\"\\nData types:\\n{df.dtypes}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFinal shape: (977, 13)\nMissing values: 0\nDuplicates: 0\nUnique field_of_study: ['Business' 'STEM' 'Social Sciences' 'Arts & Humanities' 'Health Sciences']\n\nData types:\nstudent_id                     int64\nage                            int64\nsex                           object\nfield_of_study                object\nyear_of_study                  int64\nemployment_status             object\nincome_highest_month         float64\nincome_lowest_month          float64\nliving_with_parents           object\nfinancial_support_parents    float64\nessential_spending             int64\ndiscretionary_spending       float64\ncurrent_savings_balance        int64\ndtype: object\n```\n:::\n:::\n\n\n### 4.9 - Outlier Inspection\n\nWe inspect potential outliers visually using **boxplots** before making any decision about removing them. In financial data, extreme values are not automatically errors - they may reflect real differences in student income, support, or savings.\n\nWe therefore use this step to **identify** unusual observations, assess whether they look economically plausible, and decide whether they should be retained for the later analysis.\n\n::: {#830dda4f .cell execution_count=11}\n``` {.python .cell-code}\n# 4.9 - Inspect potential outliers with boxplots and the IQR rule\n# This step asks a different question from the validity checks above.\n# Here we are not looking for impossible values; instead, we are looking for\n# observations that sit unusually far from the middle of the distribution.\n# In finance-related survey data, such points may still be genuine, so they are\n# inspected first rather than automatically removed.\n\n# We keep the inspection focused on the original survey money variables so that\n# the reader can assess unusual raw responses directly.\noutlier_cols = ['income_highest_month', 'income_lowest_month', 'financial_support_parents',\n                'essential_spending', 'discretionary_spending', 'current_savings_balance']\n\n# Boxplots visualise the centre, spread, and tails of each variable.\n# Points beyond the whiskers are potential outliers under the default boxplot rule.\nfig, axes = plt.subplots(len(outlier_cols), 1, figsize=(10, 14))\nfor ax, col in zip(axes, outlier_cols):\n    sns.boxplot(x=df[col], ax=ax, color='#90CAF9')\n    ax.set_title(f'Boxplot - {col}', fontsize=11)\n    ax.set_xlabel('')\nplt.tight_layout()\nplt.show()\n\n# The 1.5*IQR rule is a standard numerical summary of the same idea.\n# Q1 and Q3 are the 25th and 75th percentiles, and the interquartile range (IQR)\n# measures the width of the middle 50% of the data.\n# Any value below Q1 - 1.5*IQR or above Q3 + 1.5*IQR is flagged as a potential outlier.\noutlier_summary = []\nfor col in outlier_cols:\n    q1 = df[col].quantile(0.25)\n    q3 = df[col].quantile(0.75)\n    iqr = q3 - q1\n    lower = q1 - 1.5 * iqr\n    upper = q3 + 1.5 * iqr\n\n    # Count how many observations fall outside the standard IQR thresholds.\n    # These are 'potential' outliers, not automatic errors.\n    n_outliers = ((df[col] < lower) | (df[col] > upper)).sum()\n\n    outlier_summary.append({\n        'Variable': col,\n        'Q1': round(q1, 1),\n        'Q3': round(q3, 1),\n        'IQR': round(iqr, 1),\n        'Lower bound': round(lower, 1),\n        'Upper bound': round(upper, 1),\n        'Potential outliers': int(n_outliers)\n    })\n\noutlier_df = pd.DataFrame(outlier_summary)\nprint('Potential outliers based on the 1.5*IQR rule:\\n')\nprint(outlier_df.to_string(index=False))\n\nprint('\\nInterpretation: the flagged observations are inspected but retained,')\nprint('because they remain economically plausible for heterogeneous student finances.')\n```\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-12-output-1.png){width=950 height=1333}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nPotential outliers based on the 1.5*IQR rule:\n\n                 Variable    Q1     Q3    IQR  Lower bound  Upper bound  Potential outliers\n     income_highest_month 880.0 1720.0  840.0       -380.0       2980.0                   0\n      income_lowest_month 110.0  690.0  580.0       -760.0       1560.0                 185\nfinancial_support_parents  40.0  450.0  410.0       -575.0       1065.0                   0\n       essential_spending 330.0 1060.0  730.0       -765.0       2155.0                   0\n   discretionary_spending  80.0  500.0  420.0       -550.0       1130.0                  72\n  current_savings_balance 475.0 4725.0 4250.0      -5900.0      11100.0                  83\n\nInterpretation: the flagged observations are inspected but retained,\nbecause they remain economically plausible for heterogeneous student finances.\n```\n:::\n:::\n\n\n## Section 5: Exploratory Data Analysis\n\nBefore building regression models, we explore the data to understand distributions and group differences. Our key comparison is between students **living with parents** and those **renting / living independently**.\n\nThis section begins with **feature engineering**, where we construct additional variables from the raw survey responses so that the financial patterns in the data can be analysed more clearly. The engineered variables are:\n\n- `avg_income` - an estimate of typical monthly income, calculated as the midpoint between the highest-income and lowest-income month\n- `income_std` - a measure of income volatility, showing how stable or unstable income is across months\n- `monthly_savings` - an estimated monthly surplus after income and parental support are compared against essential and discretionary spending\n- `saving_rate` - monthly savings expressed as a proportion of average income, which helps compare financial discipline across students with different income levels\n- `saving_potential` - the amount remaining after essential spending only, which captures the student's structural room to save before discretionary choices are made\n\nThese variables help us distinguish between **financial capacity** and **financial behaviour**. In particular, `saving_potential` tells us how much a student could save based on their basic budget position, while `discretionary_spending` and `monthly_savings` help show whether that potential is actually converted into progress toward long-term goals.\n\n::: {#72102aac .cell execution_count=12}\n``` {.python .cell-code}\n# 5.1 — Feature Engineering: create derived columns from raw survey data\n# We engineer new variables that capture financial behaviour patterns not directly\n# observable in the raw data. These will serve as both EDA tools and regression predictors.\n\n# --- Average monthly income ---\n# The survey reports best and worst months; we take the midpoint as the typical month.\ndf['avg_income'] = (df['income_highest_month'] + df['income_lowest_month']) / 2\n\n# --- Income volatility ---\n# We use the half-range (max - min) / 2 as a proxy for income volatility.\n# Note: this is NOT the formal standard deviation — we only have two data points\n# per student (best and worst month), so the half-range is the best available\n# measure of how much their income fluctuates.\ndf['income_std'] = (df['income_highest_month'] - df['income_lowest_month']) / 2\n\n# --- Estimated monthly savings ---\n# The raw survey includes current savings balance, but not an explicit monthly flow.\n# We therefore engineer net monthly savings as the remaining surplus after essential\n# and discretionary spending.\ndf['monthly_savings'] = (\n    df['avg_income']\n    + df['financial_support_parents']\n    - df['essential_spending']\n    - df['discretionary_spending']\n)\n\n# --- Saving rate ---\n# Proportion of income that ends up as savings. Replace zero income with NaN to avoid\n# division by zero.\ndf['saving_rate'] = df['monthly_savings'] / df['avg_income'].replace(0, np.nan)\n\n# --- Saving potential ---\n# The maximum a student COULD save if they had zero discretionary spending.\n# This is the budget room available after essential costs.\ndf['saving_potential'] = df['avg_income'] + df['financial_support_parents'] - df['essential_spending']\n\nprint(\"Descriptive statistics for numeric variables:\")\ndf.describe().round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDescriptive statistics for numeric variables:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>student_id</th>\n      <th>age</th>\n      <th>year_of_study</th>\n      <th>income_highest_month</th>\n      <th>income_lowest_month</th>\n      <th>financial_support_parents</th>\n      <th>essential_spending</th>\n      <th>discretionary_spending</th>\n      <th>current_savings_balance</th>\n      <th>avg_income</th>\n      <th>income_std</th>\n      <th>monthly_savings</th>\n      <th>saving_rate</th>\n      <th>saving_potential</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>977.0</td>\n      <td>853.0</td>\n      <td>977.0</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>511.9</td>\n      <td>20.5</td>\n      <td>2.3</td>\n      <td>1214.4</td>\n      <td>702.7</td>\n      <td>241.3</td>\n      <td>724.9</td>\n      <td>374.0</td>\n      <td>3921.4</td>\n      <td>958.5</td>\n      <td>255.9</td>\n      <td>101.0</td>\n      <td>0.1</td>\n      <td>475.0</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>296.8</td>\n      <td>1.9</td>\n      <td>1.1</td>\n      <td>705.4</td>\n      <td>765.8</td>\n      <td>248.2</td>\n      <td>402.4</td>\n      <td>401.0</td>\n      <td>5126.5</td>\n      <td>696.0</td>\n      <td>239.8</td>\n      <td>381.0</td>\n      <td>0.4</td>\n      <td>714.7</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>1.0</td>\n      <td>18.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>50.0</td>\n      <td>30.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>-1420.0</td>\n      <td>-4.8</td>\n      <td>-1340.0</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>257.0</td>\n      <td>19.0</td>\n      <td>1.0</td>\n      <td>880.0</td>\n      <td>110.0</td>\n      <td>40.0</td>\n      <td>330.0</td>\n      <td>80.0</td>\n      <td>475.0</td>\n      <td>685.0</td>\n      <td>75.0</td>\n      <td>-105.0</td>\n      <td>0.0</td>\n      <td>-45.0</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>513.0</td>\n      <td>20.0</td>\n      <td>2.0</td>\n      <td>1120.0</td>\n      <td>520.0</td>\n      <td>150.0</td>\n      <td>750.0</td>\n      <td>240.0</td>\n      <td>2300.0</td>\n      <td>825.0</td>\n      <td>215.0</td>\n      <td>110.0</td>\n      <td>0.2</td>\n      <td>400.0</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>767.0</td>\n      <td>21.0</td>\n      <td>3.0</td>\n      <td>1720.0</td>\n      <td>690.0</td>\n      <td>450.0</td>\n      <td>1060.0</td>\n      <td>500.0</td>\n      <td>4725.0</td>\n      <td>985.0</td>\n      <td>345.0</td>\n      <td>270.0</td>\n      <td>0.3</td>\n      <td>730.0</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>1024.0</td>\n      <td>28.0</td>\n      <td>4.0</td>\n      <td>2810.0</td>\n      <td>2810.0</td>\n      <td>850.0</td>\n      <td>1840.0</td>\n      <td>2110.0</td>\n      <td>36525.0</td>\n      <td>2810.0</td>\n      <td>1050.0</td>\n      <td>1345.0</td>\n      <td>0.8</td>\n      <td>2620.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#e224a466 .cell execution_count=13}\n``` {.python .cell-code}\n# 5.2 — Group comparison: mean values by living situation\n# This is the first direct test of our hypothesis: do at-home students have\n# different financial profiles than renters? We compare mean income, spending,\n# and savings across the two groups. Key things to look for:\n#   - Higher saving_potential for at-home students (lower essential spending = no rent)\n#   - Whether at-home students also have higher discretionary spending (overspend?)\ncomparison_cols = ['avg_income', 'financial_support_parents', 'essential_spending',\n                   'discretionary_spending', 'monthly_savings', 'current_savings_balance']\n\ngroup_means = df.groupby('living_with_parents')[comparison_cols].mean().round(1)\ngroup_means.index.name = 'Living with parents'\nprint(\"Group comparison - mean values by living situation:\\n\")\ngroup_means\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGroup comparison - mean values by living situation:\n\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>avg_income</th>\n      <th>financial_support_parents</th>\n      <th>essential_spending</th>\n      <th>discretionary_spending</th>\n      <th>monthly_savings</th>\n      <th>current_savings_balance</th>\n    </tr>\n    <tr>\n      <th>Living with parents</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>No</th>\n      <td>1085.1</td>\n      <td>371.5</td>\n      <td>1017.0</td>\n      <td>344.4</td>\n      <td>95.2</td>\n      <td>4232.6</td>\n    </tr>\n    <tr>\n      <th>Yes</th>\n      <td>778.3</td>\n      <td>55.8</td>\n      <td>308.7</td>\n      <td>416.1</td>\n      <td>109.2</td>\n      <td>3478.2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#dc9f5f02 .cell execution_count=14}\n``` {.python .cell-code}\n# 5.3 - Histogram: saving potential by living situation\n# Compare the distribution of structural monthly saving capacity between students\n# living with parents and those renting / living independently.\nfig, axes = plt.subplots(1, 2, figsize=(12, 5), sharey=True)\n\nfor i, (group, label, color) in enumerate([\n    ('Yes', 'Living with parents', '#2196F3'),\n    ('No', 'Renting / not with parents', '#FF7043')\n]):\n    data = df[df['living_with_parents'] == group]['saving_potential']\n    axes[i].hist(data, bins=30, color=color, edgecolor='white', alpha=0.85)\n    axes[i].axvline(data.mean(), color='black', linestyle='--', linewidth=1.5, label=f'Mean: EUR {data.mean():.0f}')\n    axes[i].set_title(label, fontsize=13)\n    axes[i].set_xlabel('Saving Potential (EUR per month)')\n    axes[i].legend()\n\naxes[0].set_ylabel('Number of Students')\nfig.suptitle('Distribution of Saving Potential by Living Situation', fontsize=14, fontweight='bold')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-15-output-1.png){width=1142 height=475}\n:::\n:::\n\n\n::: {#7571bacd .cell execution_count=15}\n``` {.python .cell-code}\n# 5.4 — Correlation heatmap for numeric variables\n# We check pairwise correlations before regression to identify:\n#   - Potential multicollinearity (r > 0.8 between predictors → inflate VIF)\n#   - Tautological relationships (variables that are arithmetic components of each other)\n#   - Variables that strongly correlate with our dependent variables (good predictors)\n# High correlations here guide which variables to include/exclude in regression.\n\nnumeric_vars = ['avg_income', 'income_std', 'saving_rate', 'saving_potential',\n                'financial_support_parents', 'essential_spending',\n                'discretionary_spending', 'monthly_savings', 'current_savings_balance', 'age']\n\ncorr_matrix = df[numeric_vars].corr().round(2)\n\nfig, ax = plt.subplots(figsize=(9, 7))\nsns.heatmap(corr_matrix, annot=True, cmap='RdBu_r', center=0, vmin=-1, vmax=1,\n            square=True, linewidths=0.5, ax=ax, fmt='.2f')\nax.set_title('Correlation Matrix - Numeric Variables', fontsize=14, fontweight='bold')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-16-output-1.png){width=743 height=660}\n:::\n:::\n\n\n### 5.4 — Correlation Matrix\n\n**Purpose**: We compute pairwise Pearson correlations before building regressions to (1) understand which financial variables move together, (2) flag potential multicollinearity that could destabilise coefficient estimates, and (3) guide variable selection for our models.\n\n**Key findings and regression implications**:\n\n- **`saving_potential` ↔ `avg_income`** (r = 0.88) and **↔ `financial_support_parents`** — these are arithmetic components of `saving_potential`, so including them as predictors in Regression 1 would create a near-tautological model. We exclude both from the feature matrix.\n- **`saving_potential` ↔ `discretionary_spending`** (r = 0.92) — students with more room to save tend to spend it on non-essentials. This motivates Regression 2, where we model discretionary spending as a function of `saving_potential` and living situation to quantify this behavioural leakage.\n- **`saving_potential` ↔ `monthly_savings`** (r = 0.91) — higher potential does translate into higher absolute savings, but the equally strong link to discretionary spending shows that much of the surplus leaks away.\n- **`essential_spending` ↔ `financial_support_parents`** (r = 0.54) — students with higher essential costs (likely renters) receive more parental support, partially offsetting the cost of living away from home.\n- **`age`** — near-zero correlations with all financial variables (max r = 0.24), suggesting it will not be a significant predictor in either regression. We retain it as a control but do not expect significance.\n\n**Multicollinearity note**: The high correlations among `saving_potential`, `discretionary_spending`, `monthly_savings`, and `avg_income` are expected given their arithmetic relationships. We address this in both regressions by carefully excluding variables that mechanically overlap with the dependent variable.\n\n## Section 6: Regression 1 — What Drives Saving Potential?\n\nWe use **OLS (Ordinary Least Squares)** to model what determines a student's saving potential (total income minus essential spending). This directly tests our hypothesis: does living with parents lead to higher saving potential?\n\n**OLS assumptions**:\n\n1. **Linearity** — the relationship between predictors and DV is linear\n2. **Independence** — observations are independent (cross-sectional survey, one response per student)\n3. **Homoskedasticity** — constant residual variance (tested with White's test; if violated, we use HC3 robust standard errors)\n4. **Normality of residuals** — for valid inference on small samples (with n = 977, the Central Limit Theorem provides robustness)\n5. **No perfect multicollinearity** — checked via VIF (Variance Inflation Factor)\n\n**Dependent variable**: `saving_potential` (avg_income + financial_support_parents − essential_spending)\n\n**Independent variables**:\n\n- `living_with_parents` (binary) — our key variable of interest\n- `income_std` — income volatility (half-range between best and worst month)\n- `age`\n- `year_of_study`\n- `sex` (dummy: Female; reference = Male)\n- `employment_status` (dummies: Part-time, Freelance, Full-time; reference = Unemployed)\n- `field_of_study` (dummies: Arts & Humanities, Health Sciences, STEM, Social Sciences; reference = Business)\n\n**Excluded from predictors**:\n\n- `avg_income`, `financial_support_parents`, `essential_spending` — direct arithmetic components of the dependent variable (`saving_potential = avg_income + financial_support_parents − essential_spending`). Including them would fit an accounting identity rather than reveal genuine drivers, inflating R² with mechanically determined coefficients.\n- `saving_rate`, `monthly_savings` — both are derived from `saving_potential` (`monthly_savings = saving_potential − discretionary_spending`; `saving_rate = monthly_savings / avg_income`), so including either would create an endogenous (circular) relationship.\n- `discretionary_spending` — occurs *after* saving potential is determined (it is what students do with their surplus), so it cannot be a cause of saving potential. Including it would introduce reverse causality.\n- `income_highest_month`, `income_lowest_month` — replaced by the engineered `income_std`, which captures income volatility without duplicating information already embedded in `saving_potential` via `avg_income`.\n- `current_savings_balance` — a cumulative stock (total saved to date), not a monthly flow driver. It reflects past behaviour rather than current predictors.\n\n**Sample size**: n = 977 (no rows are dropped in this specification).\n\n**Approach**:\n\n1. Create dummy variables, drop reference categories to avoid the dummy variable trap\n2. Fit OLS with `statsmodels`\n3. Run White's test for heteroskedasticity\n4. If heteroskedasticity detected → re-estimate with robust standard errors (HC3)\n5. Check multicollinearity via VIF\n\n::: {#b6445f7b .cell execution_count=16}\n``` {.python .cell-code}\n# 6.1 — Prepare variables: create dummies and set up X (features) and y (target)\n#\n# OLS regression requires all inputs to be numeric. Categorical variables (like\n# employment_status, sex, and field_of_study) must be converted to dummy (0/1)\n# variables. We use \"drop one category\" encoding to avoid the dummy variable\n# trap — perfect multicollinearity where the dummies sum to 1 (the constant).\n\n# --- Employment status dummies ---\n# Creates one binary column per category (e.g. emp_Part-time = 1 if Part-time, else 0)\n# We drop 'Unemployed' as the reference category — all employment coefficients are\n# interpreted relative to unemployed students\nemp_dummies = pd.get_dummies(df['employment_status'], prefix='emp', drop_first=False, dtype=int)\nemp_dummies = emp_dummies.drop(columns=['emp_Unemployed'])  # reference = Unemployed\n\n# --- Sex dummy ---\n# Drop 'Male' as reference — the sex_Female coefficient measures the difference\n# in saving potential for females vs males, holding all else constant\nsex_dummies = pd.get_dummies(df['sex'], prefix='sex', drop_first=False, dtype=int)\nsex_dummies = sex_dummies.drop(columns=['sex_Male'])  # reference = Male\n\n# --- Field of study dummies ---\n# Drop 'Business' as reference — all field coefficients are interpreted relative\n# to Business students\nfield_dummies = pd.get_dummies(df['field_of_study'], prefix='field', drop_first=False, dtype=int)\nfield_dummies = field_dummies.drop(columns=['field_Business'])  # reference = Business\n\n# --- Living with parents binary ---\n# Convert Yes/No string to 1/0 integer for regression\ndf['lwp_binary'] = (df['living_with_parents'] == 'Yes').astype(int)\n\n# --- Assemble the feature matrix X ---\nX = pd.concat([\n    df[['lwp_binary', 'income_std', 'age', 'year_of_study']],\n    sex_dummies,\n    emp_dummies,\n    field_dummies\n], axis=1)\n\n# --- Add constant (intercept) ---\n# statsmodels does not add an intercept by default (unlike sklearn).\n# The constant represents the baseline predicted value when all predictors are 0\n# (i.e. the reference group: male, unemployed, renting, Business student).\nX = sm.add_constant(X)\n\n# --- Dependent variable ---\n# saving_potential = avg_income + financial_support_parents - essential_spending\n# This is what we want to explain/predict with the model\ny = df['saving_potential']\n\n# --- Drop rows with NaN or inf ---\n# np.isfinite() returns False for both NaN and inf, so this mask removes all\n# problematic rows from both X and y simultaneously to keep them aligned.\nmask = np.isfinite(X).all(axis=1) & np.isfinite(y)\nX = X[mask]\ny = y[mask]\n\nprint(f\"Rows dropped (NaN/inf): {(~mask).sum()}\")\nprint(f\"Feature matrix shape: {X.shape}\")\nprint(f\"Features: {list(X.columns)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows dropped (NaN/inf): 0\nFeature matrix shape: (977, 13)\nFeatures: ['const', 'lwp_binary', 'income_std', 'age', 'year_of_study', 'sex_Female', 'emp_Freelance', 'emp_Full-time', 'emp_Part-time', 'field_Arts & Humanities', 'field_Health Sciences', 'field_STEM', 'field_Social Sciences']\n```\n:::\n:::\n\n\n::: {#fce8666b .cell execution_count=17}\n``` {.python .cell-code}\n# 6.2 — Fit OLS (Ordinary Least Squares) model and display summary\n#\n# OLS minimises the sum of squared residuals (differences between observed and\n# predicted values of saving_potential). It finds the linear combination of\n# predictors that best fits the data.\n#\n# The .fit() method estimates the coefficients (betas) and computes standard errors,\n# t-statistics, p-values, R², and other diagnostics.\n# The .summary() output shows:\n#   - Coefficient estimates and their significance (p-values)\n#   - R² (proportion of variance explained) and Adjusted R² (penalised for # of predictors)\n#   - F-statistic (overall model significance)\n#   - Durbin-Watson statistic (tests for autocorrelation in residuals)\n\nmodel = sm.OLS(y, X).fit()\nprint(model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:       saving_potential   R-squared:                       0.821\nModel:                            OLS   Adj. R-squared:                  0.818\nMethod:                 Least Squares   F-statistic:                     367.5\nDate:                Mon, 20 Apr 2026   Prob (F-statistic):               0.00\nTime:                        21:06:00   Log-Likelihood:                -6967.1\nNo. Observations:                 977   AIC:                         1.396e+04\nDf Residuals:                     964   BIC:                         1.402e+04\nDf Model:                          12                                         \nCovariance Type:            nonrobust                                         \n===========================================================================================\n                              coef    std err          t      P>|t|      [0.025      0.975]\n-------------------------------------------------------------------------------------------\nconst                    -577.9848    139.976     -4.129      0.000    -852.678    -303.291\nlwp_binary                381.3160     20.829     18.307      0.000     340.441     422.191\nincome_std                  0.6585      0.084      7.848      0.000       0.494       0.823\nage                         1.3729      7.500      0.183      0.855     -13.345      16.091\nyear_of_study              -0.3998     12.728     -0.031      0.975     -25.377      24.578\nsex_Female                 19.8482     19.559      1.015      0.310     -18.534      58.231\nemp_Freelance             365.7020     57.778      6.329      0.000     252.317     479.087\nemp_Full-time            2097.8611     33.100     63.380      0.000    2032.905    2162.817\nemp_Part-time             616.7018     28.822     21.397      0.000     560.141     673.262\nfield_Arts & Humanities   -73.3329     28.648     -2.560      0.011    -129.553     -17.113\nfield_Health Sciences     -57.9760     32.952     -1.759      0.079    -122.641       6.689\nfield_STEM                -16.3699     27.060     -0.605      0.545     -69.473      36.733\nfield_Social Sciences     -94.4212     33.482     -2.820      0.005    -160.127     -28.715\n==============================================================================\nOmnibus:                       48.385   Durbin-Watson:                   2.079\nProb(Omnibus):                  0.000   Jarque-Bera (JB):              155.176\nSkew:                          -0.086   Prob(JB):                     2.01e-34\nKurtosis:                       4.945   Cond. No.                     5.07e+03\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n[2] The condition number is large, 5.07e+03. This might indicate that there are\nstrong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n::: {#1fae695a .cell execution_count=18}\n``` {.python .cell-code}\n# 6.3 — Diagnostics: White's test for heteroskedasticity + VIF for multicollinearity\n#\n# Two key assumptions of OLS must be checked before trusting the standard errors:\n# 1. Homoskedasticity — the variance of residuals should be constant across all\n#    levels of the predictors. If it varies (heteroskedasticity), standard errors\n#    are biased, making t-tests and p-values unreliable.\n# 2. No severe multicollinearity — predictors should not be too highly correlated\n#    with each other. If they are, individual coefficient estimates become unstable.\n\n# --- White's test ---\n# H0: residuals are homoskedastic (constant variance)\n# H1: residuals are heteroskedastic (variance depends on predictors)\n# If p-value < 0.05 → reject H0 → heteroskedasticity present → need robust SEs\nwhite_test = het_white(model.resid, model.model.exog)\nlabels = ['Test Statistic', 'p-value (White)', 'F-statistic', 'F p-value']\nprint(\"=== White's Test for Heteroskedasticity ===\")\nfor label, val in zip(labels, white_test):\n    print(f\"  {label}: {val:.4f}\")\n\nif white_test[1] < 0.05:\n    print(\"\\n  → p < 0.05: heteroskedasticity detected. We will re-estimate with robust SEs (HC3).\")\nelse:\n    print(\"\\n  → p > 0.05: no evidence of heteroskedasticity.\")\n\n# --- VIF (Variance Inflation Factor) ---\n# VIF measures how much the variance of a coefficient is inflated due to correlation\n# with other predictors. Calculated as: VIF_j = 1 / (1 - R²_j), where R²_j is\n# the R-squared from regressing predictor j on all other predictors.\n# Rule of thumb:\n#   VIF < 5  → no concern\n#   VIF 5-10 → moderate, worth monitoring\n#   VIF > 10 → problematic multicollinearity, coefficient may be unreliable\nprint(\"\\n=== Variance Inflation Factors (VIF) ===\")\nvif_data = pd.DataFrame({\n    'Variable': X.columns,\n    'VIF': [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]\n})\n# Exclude constant from display (its VIF is not meaningful)\nprint(vif_data[vif_data['Variable'] != 'const'].to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== White's Test for Heteroskedasticity ===\n  Test Statistic: 242.6743\n  p-value (White): 0.0000\n  F-statistic: 4.1493\n  F p-value: 0.0000\n\n  → p < 0.05: heteroskedasticity detected. We will re-estimate with robust SEs (HC3).\n\n=== Variance Inflation Factors (VIF) ===\n               Variable      VIF\n             lwp_binary 1.107321\n             income_std 4.260711\n                    age 2.071253\n          year_of_study 2.069157\n             sex_Female 1.006760\n          emp_Freelance 4.934977\n          emp_Full-time 1.771213\n          emp_Part-time 2.154752\nfield_Arts & Humanities 1.463608\n  field_Health Sciences 1.327754\n             field_STEM 1.487469\n  field_Social Sciences 1.317326\n```\n:::\n:::\n\n\n::: {#8034f5ee .cell execution_count=19}\n``` {.python .cell-code}\n# 6.4 — Re-estimate with robust standard errors (HC3)\n#\n# Since White's test confirmed heteroskedasticity, the standard OLS standard errors\n# are unreliable. We re-estimate using HC3 (Heteroskedasticity-Consistent) standard errors.\n#\n# Key points:\n# - The coefficient estimates (betas) do NOT change — they are still OLS estimates\n# - Only the standard errors change → which affects t-statistics, p-values, and\n#   confidence intervals\n# - HC3 applies a leverage-based correction: observations with high leverage (unusual\n#   predictor values) get larger corrections, making HC3 more conservative than HC0/HC1\n# - HC3 is preferred for smaller samples as it avoids underestimating standard errors\n#\n# cov_type='HC3' tells statsmodels to use the MacKinnon & White (1985) HC3 estimator\n\nmodel_robust = sm.OLS(y, X).fit(cov_type='HC3')\nprint(model_robust.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:       saving_potential   R-squared:                       0.821\nModel:                            OLS   Adj. R-squared:                  0.818\nMethod:                 Least Squares   F-statistic:                     329.8\nDate:                Mon, 20 Apr 2026   Prob (F-statistic):               0.00\nTime:                        21:06:00   Log-Likelihood:                -6967.1\nNo. Observations:                 977   AIC:                         1.396e+04\nDf Residuals:                     964   BIC:                         1.402e+04\nDf Model:                          12                                         \nCovariance Type:                  HC3                                         \n===========================================================================================\n                              coef    std err          z      P>|z|      [0.025      0.975]\n-------------------------------------------------------------------------------------------\nconst                    -577.9848    185.508     -3.116      0.002    -941.574    -214.396\nlwp_binary                381.3160     18.593     20.509      0.000     344.875     417.757\nincome_std                  0.6585      0.073      9.065      0.000       0.516       0.801\nage                         1.3729      9.947      0.138      0.890     -18.122      20.868\nyear_of_study              -0.3998     14.381     -0.028      0.978     -28.585      27.785\nsex_Female                 19.8482     19.595      1.013      0.311     -18.558      58.254\nemp_Freelance             365.7020     45.808      7.983      0.000     275.919     455.485\nemp_Full-time            2097.8611     35.590     58.945      0.000    2028.106    2167.616\nemp_Part-time             616.7018     22.606     27.280      0.000     572.394     661.009\nfield_Arts & Humanities   -73.3329     28.160     -2.604      0.009    -128.526     -18.140\nfield_Health Sciences     -57.9760     36.152     -1.604      0.109    -128.833      12.881\nfield_STEM                -16.3699     26.387     -0.620      0.535     -68.088      35.348\nfield_Social Sciences     -94.4212     36.119     -2.614      0.009    -165.212     -23.630\n==============================================================================\nOmnibus:                       48.385   Durbin-Watson:                   2.079\nProb(Omnibus):                  0.000   Jarque-Bera (JB):              155.176\nSkew:                          -0.086   Prob(JB):                     2.01e-34\nKurtosis:                       4.945   Cond. No.                     5.07e+03\n==============================================================================\n\nNotes:\n[1] Standard Errors are heteroscedasticity robust (HC3)\n[2] The condition number is large, 5.07e+03. This might indicate that there are\nstrong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n### Regression 1 — Interpretation\n\n**Model fit**: R² = 0.821 (Adj. R² = 0.818), meaning our model explains 82.1% of the variation in saving potential using demographic and behavioural predictors. \n\n**Key coefficients** (from the HC3 robust model, n = 977):\n\n| Variable | Coefficient | p-value | Interpretation |\n|---|---|---|---|\n| **`lwp_binary`** | **+381.32** | **< 0.001** | Students living at home have ~€381 higher saving potential than renters, holding all else constant. This confirms the core hypothesis — living at home provides a substantial structural advantage through lower essential spending (no rent). |\n| **`income_std`** | +0.66 | < 0.001 | Each €1 increase in income volatility (half-range between best and worst month) adds €0.66 to saving potential. |\n| **`age`** | +1.37 | 0.890 | **Not significant.** Age has no meaningful effect on saving potential once employment and living situation are controlled for. |\n| **`year_of_study`** | −0.40 | 0.978 | **Not significant.** Academic progression does not affect saving potential. |\n| **`sex_Female`** | +19.85 | 0.311 | **Not significant.** No statistically significant gender difference in saving potential. |\n| **`emp_Freelance`** | **+365.70** | **< 0.001** | Freelancers have ~€366 higher saving potential than unemployed students (the reference), reflecting their earning capacity despite income volatility. |\n| **`emp_Full-time`** | **+2,097.86** | **< 0.001** | Full-time workers have ~€2,098 higher saving potential than unemployed students — by far the largest coefficient. |\n| **`emp_Part-time`** | **+616.70** | **< 0.001** | Part-time workers have ~€617 higher saving potential than unemployed students, a significant income advantage. |\n| **`field_Arts & Humanities`** | −73.33 | 0.009 | Arts & Humanities students have ~€73 lower saving potential than Business students (the reference). |\n| **`field_Health Sciences`** | −57.98 | 0.109 | **Not significant.** No statistically significant difference from Business students. |\n| **`field_STEM`** | −16.37 | 0.535 | **Not significant.** No statistically significant difference from Business students. |\n| **`field_Social Sciences`** | **−94.42** | **0.009** | Social Sciences students have ~€94 lower saving potential than Business students — the largest field effect. |\n\n**Diagnostics**:\n\n- **White's test** (p ≈ 0.000): Highly significant — heteroskedasticity is present. The standard OLS standard errors are unreliable, confirming the need for HC3 robust standard errors. The HC3 model keeps the same coefficients but adjusts standard errors (and therefore p-values) to account for non-constant residual variance.\n- **VIF**: All predictors have VIF below 5:\n  - `lwp_binary`: 1.11 — no concern\n  - `income_std`: 4.26 — moderate, acceptable\n  - `emp_Freelance`: 4.93 — moderate, acceptable\n  - `age`: 2.07, `year_of_study`: 2.07 — no concern (mild correlation between the two is expected)\n  - `emp_Part-time`: 2.15, `emp_Full-time`: 1.77 — no concern\n  - All field dummies below 1.49 — no concern\n  - `sex_Female`: 1.01 — no concern\n\n**Implication for StepStone**: The three dominant predictors of saving potential are employment status (`emp_Full-time` = +€2,098), living situation (`lwp_binary` = +€381), and field of study (Social Sciences = −€94, Arts & Humanities = −€73 vs Business). Students living at home with part-time or full-time work are best positioned to save. The app should target at-home students and employed students and help them convert this structural advantage into actual savings.\n\n## Section 7: Regression 2 — What Drives Discretionary Spending?\n\nRegression 1 established that living with parents increases saving potential by ~€381, while employment status is the strongest driver overall (full-time workers gain +€2,098 and part-time workers +€617 compared to unemployed students). But do at-home and employed students actually save this advantage, or do they spend it on non-essentials? This second regression tests the **spending side** of our hypothesis by modelling discretionary spending.\n\n**Dependent variable**: `discretionary_spending`\n\n**Independent variables**:\n\n- `living_with_parents` (binary)\n- `saving_potential` — the available budget after essential costs; this directly determines how much a student *can* spend on non-essentials. Unlike in Regression 1, there is **no tautological concern** here because `discretionary_spending` is not a component of `saving_potential`\n- `income_std` — income volatility\n- `age`\n- `year_of_study`\n- `sex` (dummy: Female; reference = Male)\n- `employment_status` (dummies: Part-time, Freelance, Full-time; reference = Unemployed)\n- `field_of_study` (dummies: Arts & Humanities, Health Sciences, STEM, Social Sciences; reference = Business)\n\n**Excluded from predictors**:\n\n- `saving_rate`, `monthly_savings` — both are derived from `saving_potential` and `discretionary_spending` (`monthly_savings = saving_potential − discretionary_spending`; `saving_rate = monthly_savings / avg_income`). Including either would create an endogenous (circular) relationship — the predictor would already contain the dependent variable, biasing the estimates.\n- `avg_income`, `financial_support_parents`, `essential_spending` — direct arithmetic components of `saving_potential`, which is already included as a predictor. Adding them would introduce severe multicollinearity without additional explanatory value.\n- `income_highest_month`, `income_lowest_month` — replaced by the engineered `income_std`.\n- `current_savings_balance` — a cumulative stock (total saved to date), not a driver of current monthly spending.\n\n**Sample size**: n = 977 (no rows are dropped in this model).\n\n**Approach**: Same diagnostic workflow as Regression 1 — OLS → White's test → VIF → HC3 if needed.\n\n::: {#625c97c0 .cell execution_count=20}\n``` {.python .cell-code}\n# 7.1 — Prepare variables for Regression 2: X2 (features) and y2 (target)\n#\n# We reuse the dummy variables created in Section 6 (emp_dummies, sex_dummies,\n# field_dummies, lwp_binary).\n#\n# The key difference from Regression 1 is:\n#   - DV is now discretionary_spending (not saving_potential)\n#   - We INCLUDE saving_potential as a predictor — it represents how much budget\n#     a student has available for discretionary spending. This is NOT tautological\n#     because discretionary_spending is not part of the saving_potential formula.\n\n# --- Assemble the feature matrix X2 ---\nX2 = pd.concat([\n    df[['lwp_binary', 'saving_potential', 'income_std', 'age', 'year_of_study']],\n    sex_dummies,\n    emp_dummies,\n    field_dummies\n], axis=1)\n\n# Add constant (intercept) for OLS — represents expected discretionary spending\n# for the reference group: male, unemployed, renting, Business student\nX2 = sm.add_constant(X2)\n\n# --- Dependent variable ---\n# discretionary_spending: the amount students spend on non-essential items per month\ny2 = df['discretionary_spending']\n\n# --- Drop rows with NaN or inf ---\nmask2 = np.isfinite(X2).all(axis=1) & np.isfinite(y2)\nX2 = X2[mask2]\ny2 = y2[mask2]\n\nprint(f\"Rows dropped (NaN/inf): {(~mask2).sum()}\")\nprint(f\"Feature matrix shape: {X2.shape}\")\nprint(f\"Features: {list(X2.columns)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows dropped (NaN/inf): 0\nFeature matrix shape: (977, 14)\nFeatures: ['const', 'lwp_binary', 'saving_potential', 'income_std', 'age', 'year_of_study', 'sex_Female', 'emp_Freelance', 'emp_Full-time', 'emp_Part-time', 'field_Arts & Humanities', 'field_Health Sciences', 'field_STEM', 'field_Social Sciences']\n```\n:::\n:::\n\n\n::: {#0f62e1af .cell execution_count=21}\n``` {.python .cell-code}\n# 7.2 — Fit OLS model for discretionary spending\n\n\nmodel2 = sm.OLS(y2, X2).fit()\nprint(model2.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                              OLS Regression Results                              \n==================================================================================\nDep. Variable:     discretionary_spending   R-squared:                       0.867\nModel:                                OLS   Adj. R-squared:                  0.865\nMethod:                     Least Squares   F-statistic:                     482.9\nDate:                    Mon, 20 Apr 2026   Prob (F-statistic):               0.00\nTime:                            21:06:00   Log-Likelihood:                -6256.4\nNo. Observations:                     977   AIC:                         1.254e+04\nDf Residuals:                         963   BIC:                         1.261e+04\nDf Model:                              13                                         \nCovariance Type:                nonrobust                                         \n===========================================================================================\n                              coef    std err          t      P>|t|      [0.025      0.975]\n-------------------------------------------------------------------------------------------\nconst                     204.6206     68.257      2.998      0.003      70.671     338.570\nlwp_binary                 43.0680     11.688      3.685      0.000      20.131      66.005\nsaving_potential            0.4325      0.016     27.780      0.000       0.402       0.463\nincome_std                 -0.1473      0.042     -3.522      0.000      -0.229      -0.065\nage                        -2.0220      3.625     -0.558      0.577      -9.136       5.092\nyear_of_study              -0.1300      6.152     -0.021      0.983     -12.204      11.944\nsex_Female                 12.3558      9.459      1.306      0.192      -6.207      30.919\nemp_Freelance              50.3683     28.503      1.767      0.078      -5.567     106.303\nemp_Full-time             162.7018     36.369      4.474      0.000      91.330     234.073\nemp_Part-time             -22.2330     16.920     -1.314      0.189     -55.437      10.971\nfield_Arts & Humanities   -27.3624     13.895     -1.969      0.049     -54.630      -0.095\nfield_Health Sciences       6.4040     15.954      0.401      0.688     -24.904      37.712\nfield_STEM                -13.9874     13.083     -1.069      0.285     -39.661      11.686\nfield_Social Sciences     -12.4005     16.251     -0.763      0.446     -44.292      19.491\n==============================================================================\nOmnibus:                      168.546   Durbin-Watson:                   1.882\nProb(Omnibus):                  0.000   Jarque-Bera (JB):              559.895\nSkew:                           0.823   Prob(JB):                    2.63e-122\nKurtosis:                       6.323   Cond. No.                     1.27e+04\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n[2] The condition number is large, 1.27e+04. This might indicate that there are\nstrong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n::: {#f305019d .cell execution_count=22}\n``` {.python .cell-code}\n# 7.3 — Diagnostics: White's test for heteroskedasticity + VIF for multicollinearity\n#\n# Same diagnostic checks as Regression 1:\n# - White's test checks if residual variance is constant (homoskedasticity assumption)\n# - VIF checks if predictors are too correlated with each other (multicollinearity)\n# If White's test is significant → we need HC3 robust standard errors\n\n# --- White's test ---\nwhite_test2 = het_white(model2.resid, model2.model.exog)\nlabels = ['Test Statistic', 'p-value (White)', 'F-statistic', 'F p-value']\nprint(\"=== White's Test for Heteroskedasticity ===\")\nfor label, val in zip(labels, white_test2):\n    print(f\"  {label}: {val:.4f}\")\n\nif white_test2[1] < 0.05:\n    print(\"\\n  → p < 0.05: heteroskedasticity detected. We will re-estimate with robust SEs (HC3).\")\nelse:\n    print(\"\\n  → p > 0.05: no evidence of heteroskedasticity.\")\n\n# --- VIF ---\nprint(\"\\n=== Variance Inflation Factors (VIF) ===\")\nvif_data2 = pd.DataFrame({\n    'Variable': X2.columns,\n    'VIF': [variance_inflation_factor(X2.values, i) for i in range(X2.shape[1])]\n})\nprint(vif_data2[vif_data2['Variable'] != 'const'].to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== White's Test for Heteroskedasticity ===\n  Test Statistic: 338.6557\n  p-value (White): 0.0000\n  F-statistic: 5.4903\n  F p-value: 0.0000\n\n  → p < 0.05: heteroskedasticity detected. We will re-estimate with robust SEs (HC3).\n\n=== Variance Inflation Factors (VIF) ===\n               Variable      VIF\n             lwp_binary 1.492293\n       saving_potential 5.574795\n             income_std 4.532931\n                    age 2.071325\n          year_of_study 2.069159\n             sex_Female 1.007836\n          emp_Freelance 5.140064\n          emp_Full-time 9.151839\n          emp_Part-time 3.178118\nfield_Arts & Humanities 1.473556\n  field_Health Sciences 1.332018\n             field_STEM 1.488033\n  field_Social Sciences 1.328194\n```\n:::\n:::\n\n\n::: {#8bc0e5f7 .cell execution_count=23}\n``` {.python .cell-code}\n# 7.4 — Re-estimate with robust standard errors (HC3)\n#\n# White's test confirmed heteroskedasticity (p ≈ 0.000), so the standard OLS\n# standard errors are unreliable. We re-estimate with HC3 robust standard errors.\n\nmodel2_robust = sm.OLS(y2, X2).fit(cov_type='HC3')\nprint(model2_robust.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                              OLS Regression Results                              \n==================================================================================\nDep. Variable:     discretionary_spending   R-squared:                       0.867\nModel:                                OLS   Adj. R-squared:                  0.865\nMethod:                     Least Squares   F-statistic:                     174.4\nDate:                    Mon, 20 Apr 2026   Prob (F-statistic):          2.25e-242\nTime:                            21:06:00   Log-Likelihood:                -6256.4\nNo. Observations:                     977   AIC:                         1.254e+04\nDf Residuals:                         963   BIC:                         1.261e+04\nDf Model:                              13                                         \nCovariance Type:                      HC3                                         \n===========================================================================================\n                              coef    std err          z      P>|z|      [0.025      0.975]\n-------------------------------------------------------------------------------------------\nconst                     204.6206     70.731      2.893      0.004      65.991     343.251\nlwp_binary                 43.0680     13.846      3.111      0.002      15.931      70.205\nsaving_potential            0.4325      0.022     19.483      0.000       0.389       0.476\nincome_std                 -0.1473      0.039     -3.743      0.000      -0.224      -0.070\nage                        -2.0220      3.793     -0.533      0.594      -9.456       5.412\nyear_of_study              -0.1300      6.102     -0.021      0.983     -12.089      11.829\nsex_Female                 12.3558      9.555      1.293      0.196      -6.372      31.083\nemp_Freelance              50.3683     21.967      2.293      0.022       7.313      93.423\nemp_Full-time             162.7018     47.243      3.444      0.001      70.108     255.296\nemp_Part-time             -22.2330     17.067     -1.303      0.193     -55.683      11.217\nfield_Arts & Humanities   -27.3624     13.351     -2.049      0.040     -53.530      -1.195\nfield_Health Sciences       6.4040     17.662      0.363      0.717     -28.214      41.022\nfield_STEM                -13.9874     13.137     -1.065      0.287     -39.736      11.761\nfield_Social Sciences     -12.4005     15.451     -0.803      0.422     -42.683      17.882\n==============================================================================\nOmnibus:                      168.546   Durbin-Watson:                   1.882\nProb(Omnibus):                  0.000   Jarque-Bera (JB):              559.895\nSkew:                           0.823   Prob(JB):                    2.63e-122\nKurtosis:                       6.323   Cond. No.                     1.27e+04\n==============================================================================\n\nNotes:\n[1] Standard Errors are heteroscedasticity robust (HC3)\n[2] The condition number is large, 1.27e+04. This might indicate that there are\nstrong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n### Regression 2 — Interpretation\n\n**Model fit**: R² = 0.867 (Adj. R² = 0.865), meaning our model explains 86.7% of the variation in discretionary spending. This is a strong fit — the available budget (`saving_potential`) and employment status are powerful predictors of how much students spend on non-essentials.\n\n**Key coefficients** (from the HC3 robust model, n = 977):\n\n| Variable | Coefficient | p-value | Interpretation |\n|---|---|---|---|\n| **`lwp_binary`** | **+43.07** | **0.002** | Students living at home spend ~€43 more per month on discretionary items than renters, *even after controlling for their available budget*. |\n| **`saving_potential`** | +0.43 | < 0.001 | For every additional €1 of available budget (income + support − essentials), students spend €0.43 on discretionary items. This means 43% of any budget increase goes to non-essentials rather than savings — a strong marginal propensity to consume. |\n| **`income_std`** | −0.15 | < 0.001 | Students with more volatile income spend slightly less on discretionary items. Income uncertainty appears to encourage more cautious spending — a rational response to unpredictable earnings. |\n| **`age`** | −2.02 | 0.594 | **Not significant.** Age does not affect discretionary spending once budget and employment are controlled for. |\n| **`year_of_study`** | −0.13 | 0.983 | **Not significant.** Academic progression has no effect on discretionary spending. |\n| **`sex_Female`** | +12.36 | 0.196 | **Not significant.** No statistically significant gender difference in discretionary spending. |\n| **`emp_Freelance`** | +50.37 | 0.022 | Freelancers spend ~€50 more on discretionary items than unemployed students, beyond what their higher saving potential already explains. |\n| **`emp_Full-time`** | **+162.70** | **0.001** | Full-time workers spend ~€163 more on discretionary items than unemployed students, the largest effect. |\n| **`emp_Part-time`** | −22.23 | 0.193 | **Not significant.** Part-time workers do not spend significantly differently from unemployed students on discretionary items, once budget is controlled for. |\n| **`field_Arts & Humanities`** | −27.36 | 0.040 | Arts & Humanities students spend ~€27 less on discretionary items than Business students. |\n| **`field_Health Sciences`** | +6.40 | 0.717 | **Not significant.** No difference from Business students. |\n| **`field_STEM`** | −13.99 | 0.287 | **Not significant.** No difference from Business students. |\n| **`field_Social Sciences`** | −12.40 | 0.422 | **Not significant.** No difference from Business students despite having significantly lower saving potential in Regression 1 (−€94). |\n\n**Diagnostics**:\n\n- **White's test** (p ≈ 0.000): Heteroskedasticity confirmed — HC3 robust standard errors are necessary and used above.\n- **VIF**: All predictors have VIF below 10:\n  - `lwp_binary`: 1.49 — no concern\n  - `saving_potential`: 5.57 — moderate, acceptable \n  - `income_std`: 4.53 — moderate, acceptable\n  - `emp_Freelance`: 5.14 — moderate, acceptable\n  - `emp_Full-time`: 9.15 — approaching the threshold but acceptable\n  - `age`: 2.07, `year_of_study`: 2.07 — no concern\n  - `emp_Part-time`: 3.18 — no concern\n  - All field dummies below 1.49 — no concern\n  - `sex_Female`: 1.01 — no concern\n\n**Connecting Regression 1 and 2 — the StepStone opportunity**:\n\nRegression 1 showed that at-home students have €381 more saving potential than renters. Regression 2 shows they spend €43 more on discretionary items, even after controlling for that budget advantage. At the same time, full-time employees have both high saving potential (+€2,098) and high discretionary spending (+€163), suggesting that higher earnings lead to higher consumption rather than proportionally higher savings. Finally, for every additional euro of available budget, students spend 43 cents on discretionary items rather than saving it.\n\nThis shows that there is strong potential for StepStone to improve the financial habits of students who have the means to save more, and help them achieve their major financial goals sooner.\n\n## Section 8: Time Series Forecasting — Irish House Prices\n\nTo estimate when a student can afford a mortgage deposit, we need to forecast future house prices. We use the **CSO Residential Property Price Index (RPPI)** — an official monthly index published by the Central Statistics Office of Ireland (base year 2015 = 100).\n\n**Data source**: CSO Table HPM09 — National residential property price index, January 2005 to December 2025 (252 monthly observations).\n\n**Methodology**:\n\n1. **Data preparation** — load, filter, and parse the CSO data\n2. **Stationarity testing** — ADF test to check if the series has a unit root\n3. **ACF & PACF analysis** — identify candidate AR and MA orders\n4. **Model selection** — grid search across ARMA orders using AIC/BIC information criteria\n5. **ARIMA estimation** — fit the optimal model and check diagnostics (Ljung-Box, Jarque-Bera)\n6. **Train/test split & forecasting** — evaluate static vs dynamic out-of-sample forecasts\n7. **Forecast evaluation** — RMSE, MAE, MAPE to quantify prediction accuracy\n8. **Future projection** — forecast house prices 5 years ahead for the business case\n\n::: {#4a273864 .cell execution_count=24}\n``` {.python .cell-code}\n# 8.1 — Load and prepare the CSO Residential Property Price Index\n#\n# The raw CSV from the CSO contains multiple property types (national, Dublin,\n# apartments, houses, regional) and multiple statistics per type (price index,\n# 1-month change, 3-month change, 12-month change).\n# We filter to:\n#   - STATISTIC == 'HPM09C01' → the actual price index (not percentage changes)\n#   - Type == 'National - all residential properties' → broadest coverage\n#\n# The TLIST(M1) column contains dates in YYYYMM format (e.g. '200501' = Jan 2005).\n# We parse this to a proper datetime index for time series analysis.\n\nraw_hp = pd.read_csv(resolve_data_path('HPM09.20260307T190315.csv'))\n\n# Filter to national price index only\nhp = raw_hp[\n    (raw_hp['STATISTIC'] == 'HPM09C01') &\n    (raw_hp['Type of Residential Property'] == 'National - all residential properties')\n].copy()\n\n# Parse date column and convert index values to float\nhp['date'] = pd.to_datetime(hp['TLIST(M1)'], format='%Y%m')\nhp['price_index'] = pd.to_numeric(hp['VALUE'], errors='coerce')\n\n# Set date as index and keep only the price index column\nhp = hp.set_index('date').sort_index()[['price_index']].dropna()\n\n# Set frequency to month-start (required by statsmodels for ARIMA)\nhp.index.freq = 'MS'\n\nprint(f\"Series: {hp.index[0].strftime('%Y-%m')} to {hp.index[-1].strftime('%Y-%m')}\")\nprint(f\"Observations: {len(hp)}\")\nprint(f\"Index range: {hp['price_index'].min():.1f} to {hp['price_index'].max():.1f}\")\nprint(f\"Latest value: {hp['price_index'].iloc[-1]:.1f} (base 2015 = 100)\")\n\n# Plot the raw series\nfig, ax = plt.subplots(figsize=(12, 5))\nax.plot(hp.index, hp['price_index'], color='#2196F3', linewidth=1.5)\nax.axhline(y=100, color='grey', linestyle='--', alpha=0.5, label='2015 base (=100)')\nax.set_xlabel('Date')\nax.set_ylabel('Price Index (2015 = 100)')\nax.set_title('Irish Residential Property Price Index (2005–2025)', fontsize=14, fontweight='bold')\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSeries: 2005-01 to 2025-12\nObservations: 252\nIndex range: 73.4 to 204.6\nLatest value: 204.6 (base 2015 = 100)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-25-output-2.png){width=1142 height=470}\n:::\n:::\n\n\n::: {#64462661 .cell execution_count=25}\n``` {.python .cell-code}\n# 8.2 — Stationarity testing with the Augmented Dickey-Fuller (ADF) test\n#\n# ARIMA models require the series to be stationary (constant mean and variance\n# over time). The ADF test checks for a unit root:\n#   H0: The series has a unit root (non-stationary)\n#   H1: The series is stationary\n#   If p-value < 0.05 → reject H0 → series is stationary\n#   If p-value > 0.05 → fail to reject H0 → non-stationary → needs differencing\n#\n# We progressively difference until the ADF test confirms stationarity.\n\n# --- ADF on raw series ---\nadf_raw = st.adfuller(hp['price_index'], autolag='AIC')\nprint(\"=== ADF Test on Raw Price Index ===\")\nprint(f\"  Test statistic: {adf_raw[0]:.4f}\")\nprint(f\"  p-value:        {adf_raw[1]:.4f}\")\nprint(f\"  Lags used:      {adf_raw[2]}\")\nprint(f\"  Critical values: {adf_raw[4]}\")\nif adf_raw[1] > 0.05:\n    print(\"  → p > 0.05: FAIL to reject H0 — series is NON-STATIONARY (has unit root)\")\nelse:\n    print(\"  → p < 0.05: reject H0 — series is stationary\")\n\n# --- First difference (percentage change) ---\nhp['dhp'] = hp['price_index'].pct_change() * 100\nhp_diff1 = hp['dhp'].dropna()\n\nadf_diff1 = st.adfuller(hp_diff1, autolag='AIC')\nprint(\"\\n=== ADF Test on First-Differenced Series (% change) ===\")\nprint(f\"  Test statistic: {adf_diff1[0]:.4f}\")\nprint(f\"  p-value:        {adf_diff1[1]:.4f}\")\nprint(f\"  Lags used:      {adf_diff1[2]}\")\nif adf_diff1[1] > 0.05:\n    print(\"  → p > 0.05: FAIL to reject H0 — first difference is STILL NON-STATIONARY\")\n    print(\"  → One round of differencing is not enough. We need d = 2.\")\nelse:\n    print(\"  → p < 0.05: reject H0 — first-differenced series is stationary\")\n\n# --- Second difference ---\n# Since the first difference is not stationary, we difference again.\n# This is what ARIMA with d=2 does internally on the raw levels.\nhp_diff2 = hp['price_index'].diff().diff().dropna()\n\nadf_diff2 = st.adfuller(hp_diff2, autolag='AIC')\nprint(\"\\n=== ADF Test on Second-Differenced Series ===\")\nprint(f\"  Test statistic: {adf_diff2[0]:.4f}\")\nprint(f\"  p-value:        {adf_diff2[1]:.4f}\")\nprint(f\"  Lags used:      {adf_diff2[2]}\")\nif adf_diff2[1] > 0.05:\n    print(\"  → p > 0.05: FAIL to reject H0 — still non-stationary\")\nelse:\n    print(\"  → p < 0.05: reject H0 — second-differenced series is STATIONARY\")\n    print(\"  → We will use d = 2 in our ARIMA model.\")\n\n# Plot all three series\nfig, axes = plt.subplots(3, 1, figsize=(12, 10))\n\naxes[0].plot(hp.index, hp['price_index'], color='#2196F3')\naxes[0].set_title('Raw Price Index (Non-Stationary, ADF p = {:.3f})'.format(adf_raw[1]),\n                   fontsize=12, fontweight='bold')\naxes[0].set_ylabel('Index')\n\naxes[1].plot(hp_diff1.index, hp_diff1, color='#FF7043')\naxes[1].axhline(y=0, color='grey', linestyle='--', alpha=0.5)\naxes[1].set_title('First Difference — % Change (Still Non-Stationary, ADF p = {:.3f})'.format(adf_diff1[1]),\n                   fontsize=12, fontweight='bold')\naxes[1].set_ylabel('% Change')\n\naxes[2].plot(hp_diff2.index, hp_diff2, color='#4CAF50')\naxes[2].axhline(y=0, color='grey', linestyle='--', alpha=0.5)\naxes[2].set_title('Second Difference (Stationary, ADF p = {:.4f})'.format(adf_diff2[1]),\n                   fontsize=12, fontweight='bold')\naxes[2].set_ylabel('Δ²Price Index')\naxes[2].set_xlabel('Date')\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== ADF Test on Raw Price Index ===\n  Test statistic: -1.4722\n  p-value:        0.5472\n  Lags used:      9\n  Critical values: {'1%': np.float64(-3.457664132155201), '5%': np.float64(-2.8735585105960224), '10%': np.float64(-2.5731749894132916)}\n  → p > 0.05: FAIL to reject H0 — series is NON-STATIONARY (has unit root)\n\n=== ADF Test on First-Differenced Series (% change) ===\n  Test statistic: -1.7744\n  p-value:        0.3933\n  Lags used:      8\n  → p > 0.05: FAIL to reject H0 — first difference is STILL NON-STATIONARY\n  → One round of differencing is not enough. We need d = 2.\n\n=== ADF Test on Second-Differenced Series ===\n  Test statistic: -9.6397\n  p-value:        0.0000\n  Lags used:      7\n  → p < 0.05: reject H0 — second-differenced series is STATIONARY\n  → We will use d = 2 in our ARIMA model.\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-26-output-2.png){width=1142 height=950}\n:::\n:::\n\n\n::: {#24057c2a .cell execution_count=26}\n``` {.python .cell-code}\n# 8.3 — ACF & PACF analysis (Autocorrelation and Partial Autocorrelation)\n#\n# ACF and PACF help identify the order of ARMA components:\n#   - ACF (Autocorrelation Function): measures correlation between the series\n#     and its lagged values. A sharp cutoff after lag q suggests an MA(q) process.\n#   - PACF (Partial ACF): measures correlation at lag k after removing the effect\n#     of intermediate lags. A sharp cutoff after lag p suggests an AR(p) process.\n#\n# We compute these on the SECOND-differenced series, since this is the series\n# confirmed as stationary by the ADF test. ACF/PACF are only meaningful for\n# stationary data — running them on a non-stationary series produces misleading\n# results (e.g. slow ACF decay that mimics high-order AR).\n\nacf_vals = smt.acf(hp_diff2, nlags=12)\npacf_vals = smt.pacf(hp_diff2, nlags=12)\n\n# Display as a correlogram table\ncorrelogram = pd.DataFrame({\n    'Lag': range(1, 13),\n    'ACF': acf_vals[1:],\n    'PACF': pacf_vals[1:]\n}).set_index('Lag').round(3)\nprint(\"Correlogram (ACF & PACF for lags 1–12, second-differenced series):\\n\")\nprint(correlogram)\n\n# Plot ACF and PACF\nfig, axes = plt.subplots(1, 2, figsize=(14, 4))\n\n# ACF plot\naxes[0].bar(range(1, 13), acf_vals[1:], color='#2196F3', width=0.6)\naxes[0].axhline(y=1.96/np.sqrt(len(hp_diff2)), color='red', linestyle='--', alpha=0.7)\naxes[0].axhline(y=-1.96/np.sqrt(len(hp_diff2)), color='red', linestyle='--', alpha=0.7)\naxes[0].set_title('ACF — Autocorrelation Function (2nd diff)', fontweight='bold')\naxes[0].set_xlabel('Lag')\naxes[0].set_ylabel('Autocorrelation')\n\n# PACF plot\naxes[1].bar(range(1, 13), pacf_vals[1:], color='#FF7043', width=0.6)\naxes[1].axhline(y=1.96/np.sqrt(len(hp_diff2)), color='red', linestyle='--', alpha=0.7)\naxes[1].axhline(y=-1.96/np.sqrt(len(hp_diff2)), color='red', linestyle='--', alpha=0.7)\naxes[1].set_title('PACF — Partial Autocorrelation Function (2nd diff)', fontweight='bold')\naxes[1].set_xlabel('Lag')\naxes[1].set_ylabel('Partial Autocorrelation')\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCorrelogram (ACF & PACF for lags 1–12, second-differenced series):\n\n       ACF   PACF\nLag              \n1   -0.328 -0.329\n2    0.191  0.095\n3   -0.108 -0.023\n4   -0.008 -0.074\n5   -0.149 -0.182\n6   -0.070 -0.184\n7   -0.052 -0.117\n8   -0.128 -0.219\n9    0.152  0.022\n10   0.039  0.096\n11   0.019 -0.043\n12   0.116  0.058\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-27-output-2.png){width=1334 height=374}\n:::\n:::\n\n\n::: {#a890b5bf .cell execution_count=27}\n``` {.python .cell-code}\n# 8.4 — Model selection: grid search over ARMA orders using AIC and BIC\n#\n# We use an automated grid search to find the optimal AR(p) and MA(q) orders\n# for the stationary (second-differenced) series.\n#\n# arma_order_select_ic tests all combinations of p = 0..5 and q = 0..5 and returns\n# the (p, q) pair that minimises each information criterion:\n#   - AIC (Akaike Information Criterion): balances fit and complexity, tends to\n#     select slightly larger models. AIC = -2*log(L) + 2*k\n#   - BIC (Bayesian Information Criterion): penalises complexity more heavily,\n#     tends to select more parsimonious models. BIC = -2*log(L) + k*log(n)\n# where L = likelihood, k = number of parameters, n = sample size.\n#\n# The grid search runs on the second-differenced series (confirmed stationary).\n# Many complex combinations will fail to converge — this is expected and harmless;\n# the grid search tries every combination and discards the ones that don't work.\n#\n# After identifying the BIC-optimal order, we verify that the corresponding\n# ARIMA model converges when fitted on the TRAINING data (not the full dataset),\n# because that is the data the model will actually be trained on in cell 8.5.\n# If the BIC-optimal model does not converge on the training set, we fall back\n# to the next-best BIC model that does — a non-converged model has unreliable\n# parameter estimates and cannot be trusted for forecasting.\n\nres_grid = smt.arma_order_select_ic(hp_diff2, max_ar=5, max_ma=5, ic=['aic', 'bic'])\n\nprint(\"=== Optimal ARMA Orders (on second-differenced series) ===\")\nprint(f\"  AIC optimal order: AR({int(res_grid.aic_min_order[0])}), MA({int(res_grid.aic_min_order[1])})\")\nprint(f\"  BIC optimal order: AR({int(res_grid.bic_min_order[0])}), MA({int(res_grid.bic_min_order[1])})\")\n\n# --- Convergence check on training data ---\n# We use the same train/test split as cell 8.5 (last 24 months held out).\n# This ensures the model we select actually converges when trained, not just\n# when fitted on the full dataset (which has 24 more observations and may\n# converge where the training subset does not).\nsplit_idx = len(hp) - 24\ntrain_check = hp['price_index'].iloc[:split_idx]\n\nbic_table = res_grid.bic\nbic_ranked = (\n    bic_table.stack()\n    .reset_index()\n    .rename(columns={'level_0': 'p', 'level_1': 'q', 0: 'BIC'})\n    .sort_values('BIC')\n)\n\narima_order = None\nbic_optimal = (int(res_grid.bic_min_order[0]), 2, int(res_grid.bic_min_order[1]))\n\nfor _, row in bic_ranked.iterrows():\n    p, q = int(row['p']), int(row['q'])\n    candidate = (p, 2, q)\n    try:\n        with warnings.catch_warnings():\n            warnings.simplefilter(\"ignore\")\n            test_fit = smt.ARIMA(train_check, order=candidate).fit()\n        if test_fit.mle_retvals['converged']:\n            arima_order = candidate\n            if candidate == bic_optimal:\n                print(f\"\\n  BIC-optimal ARIMA{bic_optimal} converges on training data.\")\n            else:\n                print(f\"\\n  BIC-optimal ARIMA{bic_optimal} does not converge on training data.\")\n                print(f\"  → Falling back to best converging model: ARIMA{candidate}\")\n            break\n    except Exception:\n        continue\n\nprint(f\"\\n  Selected model: ARIMA{arima_order}\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\tsa\\statespace\\sarimax.py:966: UserWarning:\n\nNon-stationary starting autoregressive parameters found. Using zeros as starting parameters.\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\tsa\\statespace\\sarimax.py:978: UserWarning:\n\nNon-invertible starting MA parameters found. Using zeros as starting parameters.\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n=== Optimal ARMA Orders (on second-differenced series) ===\n  AIC optimal order: AR(5), MA(4)\n  BIC optimal order: AR(3), MA(2)\n\n  BIC-optimal ARIMA(3, 2, 2) does not converge on training data.\n  → Falling back to best converging model: ARIMA(2, 2, 4)\n\n  Selected model: ARIMA(2, 2, 4)\n```\n:::\n:::\n\n\n::: {#9c760900 .cell execution_count=28}\n``` {.python .cell-code}\n# 8.5 — Train/test split and fit ARIMA model\n#\n# We hold out the last 24 months (2 years) as a test set to evaluate forecast\n# accuracy. The model is trained on all data before that period.\n#\n# ARIMA(p, d, q) on the price index levels:\n#   - p = AR order (autoregressive: uses past values to predict current)\n#   - d = 2 (differencing order: the model internally differences twice to\n#     achieve stationarity, as confirmed by the ADF tests in cell 8.2)\n#   - q = MA order (moving average: uses past forecast errors to adjust predictions)\n#\n# Why we use ARIMA(p, 2, q) on levels rather than manual differencing with d=0:\n# When the series requires two rounds of differencing, working on levels with d=2\n# keeps the pipeline cleaner — the model handles both differencings internally and\n# produces forecasts directly in price index units, which simplifies the business\n# case in Section 9 (no need to manually invert two layers of differencing).\n#\n# The summary output includes key diagnostics:\n#   - Ljung-Box (Q): tests if residuals are white noise (want p > 0.05)\n#   - Jarque-Bera (JB): tests if residuals are normally distributed (want p > 0.05)\n#   - Heteroskedasticity (H): tests if residual variance is constant (want p > 0.05)\n\n# --- Train/test split ---\nsplit_idx = len(hp) - 24\ntrain = hp['price_index'].iloc[:split_idx]\ntest = hp['price_index'].iloc[split_idx:]\n\nprint(f\"Train set: {train.index[0].strftime('%Y-%m')} to {train.index[-1].strftime('%Y-%m')} ({len(train)} obs)\")\nprint(f\"Test set:  {test.index[0].strftime('%Y-%m')} to {test.index[-1].strftime('%Y-%m')} ({len(test)} obs)\")\n\n# --- Fit ARIMA on training data ---\nprint(f\"\\nFitting ARIMA{arima_order} on training data...\\n\")\nmodel_ts = smt.ARIMA(train, order=arima_order).fit()\nprint(model_ts.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrain set: 2005-01 to 2023-12 (228 obs)\nTest set:  2024-01 to 2025-12 (24 obs)\n\nFitting ARIMA(2, 2, 4) on training data...\n\n                               SARIMAX Results                                \n==============================================================================\nDep. Variable:            price_index   No. Observations:                  228\nModel:                 ARIMA(2, 2, 4)   Log Likelihood                -229.959\nDate:                Mon, 20 Apr 2026   AIC                            473.917\nTime:                        21:06:16   BIC                            497.861\nSample:                    01-01-2005   HQIC                           483.580\n                         - 12-01-2023                                         \nCovariance Type:                  opg                                         \n==============================================================================\n                 coef    std err          z      P>|z|      [0.025      0.975]\n------------------------------------------------------------------------------\nar.L1         -0.0004      1.849     -0.000      1.000      -3.624       3.624\nar.L2          0.4807      1.227      0.392      0.695      -1.924       2.885\nma.L1         -0.3681      1.855     -0.198      0.843      -4.005       3.269\nma.L2         -0.3058      1.917     -0.160      0.873      -4.064       3.452\nma.L3          0.0283      0.797      0.035      0.972      -1.534       1.591\nma.L4         -0.1568      0.492     -0.318      0.750      -1.122       0.808\nsigma2         0.4472      0.043     10.302      0.000       0.362       0.532\n===================================================================================\nLjung-Box (L1) (Q):                   0.01   Jarque-Bera (JB):                 0.40\nProb(Q):                              0.90   Prob(JB):                         0.82\nHeteroskedasticity (H):               0.50   Skew:                             0.10\nProb(H) (two-sided):                  0.00   Kurtosis:                         3.01\n===================================================================================\n\nWarnings:\n[1] Covariance matrix calculated using the outer product of gradients (complex-step).\n```\n:::\n:::\n\n\n::: {#413b1618 .cell execution_count=29}\n``` {.python .cell-code}\n# 8.6 — Out-of-sample forecasting: static vs dynamic\n#\n# We evaluate the model by forecasting the 24-month test period in two ways:\n#\n# 1. STATIC forecast (rolling one-step-ahead):\n#    At each time step, the model is re-estimated with all data up to t-1,\n#    then predicts one step ahead. This uses actual observed values as inputs,\n#    giving the best possible short-term forecast.\n#\n# 2. DYNAMIC forecast (multi-step-ahead):\n#    Uses only training data, then feeds its own predictions back as inputs for\n#    subsequent steps. This is more realistic for long-horizon planning (like our\n#    5-year business case), but errors compound over time.\n\nimport statsmodels.tsa.api as smt\n\n# --- Static forecast (rolling one-step-ahead) ---\n# Re-estimate the model at each step with expanding window, forecast 1 step ahead\nhistory = list(train)\nstatic_predictions = []\nfor t in range(len(test)):\n    model_rolling = smt.ARIMA(history, order=arima_order).fit()\n    pred = model_rolling.forecast(steps=1)[0]\n    static_predictions.append(pred)\n    history.append(test.iloc[t])\n\npred_static = pd.Series(static_predictions, index=test.index)\n\n# --- Dynamic forecast (multi-step-ahead from training model) ---\npred_dynamic = model_ts.predict(start=test.index[0], end=test.index[-1])\n\n# --- Plot forecasts vs actual ---\nfig, ax = plt.subplots(figsize=(12, 6))\n\n# Show last 4 years of training data for context\ncontext_start = train.index[-48] if len(train) > 48 else train.index[0]\nax.plot(train.loc[context_start:], color='#2196F3', linewidth=1.5, label='Training data')\nax.plot(test, color='black', linewidth=2, label='Actual (test set)')\nax.plot(pred_static, color='#4CAF50', linewidth=1.5, linestyle='--', label='Static forecast (1-step)')\nax.plot(pred_dynamic, color='#FF7043', linewidth=1.5, linestyle='--', label='Dynamic forecast (multi-step)')\n\nax.axvline(x=test.index[0], color='grey', linestyle=':', alpha=0.7, label='Train/test split')\nax.set_xlabel('Date')\nax.set_ylabel('Price Index')\nax.set_title(f'ARIMA{arima_order} — Out-of-Sample Forecast vs Actual', fontsize=14, fontweight='bold')\nax.legend(loc='upper left')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-30-output-2.png){width=1142 height=566}\n:::\n:::\n\n\n::: {#16d62a23 .cell execution_count=30}\n``` {.python .cell-code}\n# 8.7 — Forecast evaluation metrics\n#\n# We quantify forecast accuracy using three standard metrics:\n#\n# 1. RMSE (Root Mean Squared Error): √(mean((pred - actual)²))\n#    - In the same units as the series (index points)\n#    - Penalises large errors more heavily due to squaring\n#    - Lower = better\n#\n# 2. MAE (Mean Absolute Error): mean(|pred - actual|)\n#    - Also in the same units as the series\n#    - Treats all errors equally (no squaring)\n#    - Lower = better\n#\n# 3. MAPE (Mean Absolute Percentage Error): mean(|pred - actual| / actual) × 100\n#    - Expressed as a percentage — scale-independent\n#    - Intuitive: \"on average, the forecast is off by X%\"\n#    - Lower = better; MAPE < 5% is generally considered very good\n\n# --- Define evaluation functions ---\ndef rmse(pred, target):\n    return np.sqrt(((pred - target) ** 2).mean())\n\ndef mae(pred, target):\n    return (pred - target).abs().mean()\n\ndef mape(pred, target):\n    return ((pred - target).abs() / target).mean() * 100\n\n# --- Compute metrics for both forecast types ---\nmetrics = pd.DataFrame({\n    'Static (1-step)': [rmse(pred_static, test), mae(pred_static, test), mape(pred_static, test)],\n    'Dynamic (multi-step)': [rmse(pred_dynamic, test), mae(pred_dynamic, test), mape(pred_dynamic, test)]\n}, index=['RMSE', 'MAE', 'MAPE (%)']).round(2)\n\nprint(f\"=== Forecast Evaluation — ARIMA{arima_order} (24-month test set) ===\\n\")\nprint(metrics)\nprint(f\"\\nStatic forecast (1-step-ahead): MAPE of {mape(pred_static, test):.2f}% — very accurate\")\nprint(f\"when the model has access to the most recent actual value.\")\nprint(f\"\\nDynamic forecast (multi-step): MAPE of {mape(pred_dynamic, test):.2f}% — errors compound\")\nprint(f\"over the 24-month horizon, but accuracy remains reasonable for planning purposes.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== Forecast Evaluation — ARIMA(2, 2, 4) (24-month test set) ===\n\n          Static (1-step)  Dynamic (multi-step)\nRMSE                 0.50                  3.99\nMAE                  0.41                  3.72\nMAPE (%)             0.22                  1.93\n\nStatic forecast (1-step-ahead): MAPE of 0.22% — very accurate\nwhen the model has access to the most recent actual value.\n\nDynamic forecast (multi-step): MAPE of 1.93% — errors compound\nover the 24-month horizon, but accuracy remains reasonable for planning purposes.\n```\n:::\n:::\n\n\n::: {#55cad97f .cell execution_count=31}\n``` {.python .cell-code}\n# 8.8 — Future price forecast (10 years / 120 months ahead)\n#\n# Now we refit the ARIMA model on the FULL dataset (train + test) to use all\n# available information, then project 120 months (10 years) into the future.\n#\n# get_forecast() returns both point predictions and confidence intervals.\n# The confidence intervals widen over time because uncertainty compounds —\n# the further ahead we forecast, the less certain we are.\n#\n# To convert the index to approximate euro values, we use the known reference:\n# In 2015 (index base year = 100), the median national house price was ~€189,000 (derived from 2025 median €387,000 / index 204.6).\n# So: estimated_price = (index / 100) × €189,000\n\nPRICE_AT_BASE = 189_000  # median national house price in 2015 (index=100, derived from 2025 median €387k / index 204.6)\n\n# --- Refit on full data ---\nmodel_full = smt.ARIMA(hp['price_index'], order=arima_order).fit()\n\n# --- Forecast 120 months (10 years) ahead ---\nforecast = model_full.get_forecast(steps=120)\nforecast_mean = forecast.predicted_mean\nforecast_ci = forecast.conf_int()\n\n# --- Convert index to euro estimates ---\nforecast_eur = forecast_mean * PRICE_AT_BASE / 100\nforecast_ci_eur = forecast_ci * PRICE_AT_BASE / 100\ncurrent_price_eur = hp['price_index'].iloc[-1] * PRICE_AT_BASE / 100\n\nprint(f\"=== 10-Year House Price Forecast ===\\n\")\nprint(f\"  Current index: {hp['price_index'].iloc[-1]:.1f} → ~€{current_price_eur:,.0f}\")\nprint(f\"  +1 year:       {forecast_mean.iloc[11]:.1f} → ~€{forecast_eur.iloc[11]:,.0f}\")\nprint(f\"  +2 years:      {forecast_mean.iloc[23]:.1f} → ~€{forecast_eur.iloc[23]:,.0f}\")\nprint(f\"  +5 years:      {forecast_mean.iloc[59]:.1f} → ~€{forecast_eur.iloc[59]:,.0f}\")\nprint(f\"  +10 years:     {forecast_mean.iloc[119]:.1f} → ~€{forecast_eur.iloc[119]:,.0f}\")\n\n# --- Plot forecast with confidence interval ---\nfig, ax = plt.subplots(figsize=(14, 6))\n\n# Historical data (last 5 years for context)\nrecent = hp['price_index'].iloc[-60:]\nrecent_eur = recent * PRICE_AT_BASE / 100\nax.plot(recent_eur.index, recent_eur, color='#2196F3', linewidth=1.5, label='Historical')\n\n# Forecast\nax.plot(forecast_eur.index, forecast_eur, color='#FF7043', linewidth=2, label='Forecast')\nax.fill_between(forecast_ci_eur.index,\n                forecast_ci_eur.iloc[:, 0], forecast_ci_eur.iloc[:, 1],\n                color='#FF7043', alpha=0.15, label='95% confidence interval')\n\nax.axvline(x=hp.index[-1], color='grey', linestyle=':', alpha=0.7)\nax.set_xlabel('Date')\nax.set_ylabel('Estimated House Price (€)')\nax.set_title('Irish House Price Forecast — Next 10 Years', fontsize=14, fontweight='bold')\nax.legend()\nax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'€{x:,.0f}'))\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\uzivatel\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\statsmodels\\base\\model.py:607: ConvergenceWarning:\n\nMaximum Likelihood optimization failed to converge. Check mle_retvals\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n=== 10-Year House Price Forecast ===\n\n  Current index: 204.6 → ~€386,694\n  +1 year:       220.9 → ~€417,530\n  +2 years:      237.3 → ~€448,562\n  +5 years:      286.6 → ~€541,674\n  +10 years:     368.7 → ~€696,918\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-32-output-3.png){width=1334 height=566}\n:::\n:::\n\n\n### Section 8 — Interpretation\n\n**Data**: The CSO RPPI for national residential properties spans January 2005 to December 2025 (252 monthly observations).\n\n**Stationarity**: The raw series is non-stationary (ADF p = 0.547), as expected from the visible trend. Crucially, the **first difference is also non-stationary** (ADF p = 0.393) — one round of differencing is not enough. Only the **second difference achieves stationarity** (ADF p ≈ 0.000). This means the series is integrated of order 2, requiring d = 2 in our ARIMA model.\n\n**Why ARIMA(p, 2, q) on levels instead of manual differencing**: An alternative approach is to manually difference the series twice and then fit an ARMA(p, 0, q) model on the result. We chose to work on levels with d = 2 because it keeps the pipeline cleaner — the model handles both differencings internally and produces forecasts directly in price index units, which simplifies the business case in Section 9 (no need to manually invert two layers of differencing back to price levels).\n\n**Model selection**: The automated grid search on the second-differenced series identified the BIC-optimal order, but that model did not converge on the training data. The fallback procedure selected **ARIMA(2, 2, 4)** — the best-BIC model that converges on the training subset. This means the model uses 2 autoregressive lags and 4 moving average terms, with two rounds of internal differencing.\n\n**Coefficients**: None of the individual AR/MA coefficients are statistically significant (all p > 0.05). This is common in higher-order ARIMA models where the AR and MA terms are correlated with each other (parameter multicollinearity), inflating the standard errors. The model’s forecasting ability — reflected in the diagnostics and out-of-sample accuracy — is a better judge of quality than individual coefficient significance.\n\n**Diagnostics** (from the ARIMA summary):\n\n- **Ljung-Box (Q)**: p = 0.90 — no residual autocorrelation. The model has captured the serial dependence in the data well.\n- **Jarque-Bera (JB)**: p = 0.82 — residuals are approximately normally distributed (skew = 0.10, kurtosis = 3.01).\n- **Heteroskedasticity (H)**: p = 0.00 — residual variance is not constant. This suggests volatility clustering (likely higher variance during the post-2008 crash and COVID-era recovery). For our forecasting purpose, the point forecasts remain valid, but confidence intervals may be wider or narrower than stated in some periods.\n\n**Forecast accuracy** (24-month test set, Jan 2024 – Dec 2025):\n\n- **Static (rolling 1-step-ahead)**: MAPE = 0.22% — extremely accurate when the model has access to the most recent actual value at each step. This serves as a theoretical benchmark.\n- **Dynamic (multi-step-ahead)**: MAPE = 1.93% — errors compound over the 24-month horizon, but accuracy remains strong for house price forecasting. This is the realistic measure for our 10-year projection, as future values are unknown.\n\n**10-year projection**: Using a base price of €189,000 (2015 median, derived from the 2025 national median of €387,000 and the current index of 204.6), the model forecasts continued price growth over the next decade.\n\n## Section 9: Business Case — When Can a Student Afford a Mortgage Deposit?\n\nThis section brings together our regression findings (Sections 6–7) and the ARIMA house price forecast (Section 8) to answer the core StepStone question: **how much faster can a student reach a mortgage deposit with the app?**\n\n**Setup:**\n\n- We randomly select two students from our dataset: one **at-home student** and one **full-time employed student**\n- Under Irish Central Bank rules, a first-time buyer needs a **10% deposit** (90% LTV limit)\n- The deposit target is not fixed — it rises over time as house prices increase (from our ARIMA forecast)\n\n**Saving conversion rate:** We define the conversion rate as `monthly_savings / saving_potential` — the share of a student's available budget (after essential spending) that actually ends up as savings. Across our dataset, this rate averages only ~21%, meaning ~79% of what students *could* save is consumed by discretionary spending.\n\n**Scenarios:**\n\n- **Without app**: The student continues saving at their current conversion rate (~21% on average)\n- **With app (Conservative, 45%)**: StepStone helps the student save 45% of their saving potential — roughly doubling the current rate\n- **With app (Base, 60%)**: The student saves 60% of their saving potential\n- **With app (Optimistic, 80%)**: The student saves 80% of their saving potential\n\nThe crossover point where cumulative savings meet the deposit requirement tells us **when** (and whether) each student can afford to buy.\n\n::: {#a72f6c33 .cell execution_count=32}\n``` {.python .cell-code}\n# 9.1 — Student profiles, savings trajectories, and deposit crossover\n#\n# We select two representative students and project their savings over 10 years\n# under four scenarios (current rate + three app tiers) against the rising\n# mortgage deposit requirement from our ARIMA house price forecast.\n\n# --- Select two students (reproducible - using random_state (seed)) ---\nstudent_home = df[df['living_with_parents'] == 'Yes'].sample(n=1, random_state=42).iloc[0]\nstudent_ft = df[df['employment_status'] == 'Full-time'].sample(n=1, random_state=42).iloc[0]\n\n# --- Print profiles ---\nprofile_cols = ['age', 'year_of_study', 'living_with_parents', 'employment_status', 'field_of_study',\n                'avg_income', 'essential_spending', 'discretionary_spending',\n                'saving_potential', 'monthly_savings', 'current_savings_balance']\n\nprint(\"=== Student Profiles ===\\n\")\nfor col in profile_cols:\n    label = col.replace('_', ' ').title()\n    v1, v2 = student_home[col], student_ft[col]\n    if isinstance(v1, (int, float)) and col not in ['age', 'year_of_study']:\n        print(f\"  {label:<28s}  €{v1:>8,.0f}    €{v2:>8,.0f}\")\n    else:\n        print(f\"  {label:<28s}  {str(v1):>9s}    {str(v2):>9s}\")\n\n# Current saving rates\nrate_home = student_home['monthly_savings'] / student_home['saving_potential'] * 100\nrate_ft = student_ft['monthly_savings'] / student_ft['saving_potential'] * 100\nprint(f\"\\n  {'Current Saving Rate':<28s}  {rate_home:>8.1f}%    {rate_ft:>8.1f}%\")\n\n# --- App scenario rates ---\nSCENARIOS = {\n    'Without app':           None,   # uses actual monthly_savings\n    'Conservative (45%)':    0.45,\n    'Base (60%)':            0.60,\n    'Optimistic (80%)':      0.80,\n}\n\nCOLORS = {\n    'Without app':           '#FF7043',\n    'Conservative (45%)':    '#A5D6A7',\n    'Base (60%)':            '#4CAF50',\n    'Optimistic (80%)':      '#1B5E20',\n}\n\nSTYLES = {\n    'Without app':           '--',\n    'Conservative (45%)':    ':',\n    'Base (60%)':            '-',\n    'Optimistic (80%)':      '-',\n}\n\n# --- Compute trajectories (120 months = 10 years) ---\nmonths = np.arange(1, 121)\ndeposit_required = forecast_eur.iloc[:120] * 0.10\ndeposit_ci_lower = forecast_ci_eur.iloc[:120, 0] * 0.10\ndeposit_ci_upper = forecast_ci_eur.iloc[:120, 1] * 0.10\n\nstudents = {\n    'At-Home Student': student_home,\n    'Full-Time Worker': student_ft,\n}\n\ndef find_crossover(cumulative, deposit):\n    \"\"\"First month where cumulative savings >= deposit requirement.\"\"\"\n    for i in range(len(cumulative)):\n        if cumulative[i] >= deposit.iloc[i]:\n            return i + 1  # 1-indexed month\n    return None\n\n# --- Plot: two side-by-side panels ---\nfig, axes = plt.subplots(1, 2, figsize=(16, 7), sharey=False)\n\nresults = {}  # store crossover results for summary\n\nfor ax, (label, s) in zip(axes, students.items()):\n    balance = s['current_savings_balance']\n    results[label] = {}\n\n    # Deposit line\n    ax.plot(forecast_eur.index[:120], deposit_required, color='black', lw=2, label='10% deposit required')\n    ax.fill_between(forecast_eur.index[:120], deposit_ci_lower, deposit_ci_upper,\n                    color='grey', alpha=0.15, label='Deposit uncertainty (95% CI)')\n\n    # Savings lines\n    for scenario, rate in SCENARIOS.items():\n        if rate is None:\n            monthly = s['monthly_savings']\n        else:\n            monthly = s['saving_potential'] * rate\n        cumulative = balance + monthly * months\n\n        ax.plot(forecast_eur.index[:120], cumulative,\n                color=COLORS[scenario], lw=2, ls=STYLES[scenario],\n                label=f'{scenario} (€{monthly:,.0f}/mo)')\n\n        # Find crossover\n        cross = find_crossover(cumulative, deposit_required)\n        results[label][scenario] = cross\n\n        # Mark crossover with vertical line\n        if cross is not None and cross <= 120:\n            ax.axvline(x=forecast_eur.index[cross - 1], color=COLORS[scenario],\n                       ls=':', alpha=0.6, lw=1)\n\n    ax.set_title(label, fontsize=13, fontweight='bold')\n    ax.set_xlabel('Date')\n    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'€{x:,.0f}'))\n    ax.legend(loc='upper left', fontsize=8)\n\naxes[0].set_ylabel('Amount (€)')\nfig.suptitle('Path to Mortgage Deposit — With vs Without StepStone',\n             fontsize=15, fontweight='bold', y=1.02)\nplt.tight_layout()\nplt.show()\n\n# --- Print summary ---\nprint(f\"\\n=== Deposit Crossover Summary (10% of forecast house price) ===\")\nprint(f\"  Current house price: ~€{current_price_eur:,.0f}  →  10% deposit: ~€{current_price_eur * 0.10:,.0f}\\n\")\n\nfor label, s in students.items():\n    print(f\"  {label} (balance: €{s['current_savings_balance']:,.0f}, \"\n          f\"saves: €{s['monthly_savings']:,.0f}/mo, potential: €{s['saving_potential']:,.0f}/mo):\")\n    for scenario, cross in results[label].items():\n        if cross is not None:\n            print(f\"    {scenario:<25s}  → deposit in {cross:>3d} months ({cross/12:.1f} years)\")\n        else:\n            print(f\"    {scenario:<25s}  → NOT reached within 10 years\")\n\n    # Acceleration vs without app\n    base_cross = results[label]['Without app']\n    if base_cross is not None:\n        for scenario in ['Conservative (45%)', 'Base (60%)', 'Optimistic (80%)']:\n            app_cross = results[label][scenario]\n            if app_cross is not None:\n                saved = base_cross - app_cross\n                print(f\"    {scenario} saves {saved} months ({saved/12:.1f} years) vs no app\")\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=== Student Profiles ===\n\n  Age                                  21           19\n  Year Of Study                         3            1\n  Living With Parents                 Yes           No\n  Employment Status             Part-time    Full-time\n  Field Of Study                 Business         STEM\n  Avg Income                    €     835    €   2,430\n  Essential Spending                  160          930\n  Discretionary Spending        €     410    €     990\n  Saving Potential              €     675    €   1,500\n  Monthly Savings               €     265    €     510\n  Current Savings Balance            6750         3050\n\n  Current Saving Rate               39.3%        34.0%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](econometrics-project_files/figure-html/cell-33-output-2.png){width=1526 height=690}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=== Deposit Crossover Summary (10% of forecast house price) ===\n  Current house price: ~€386,694  →  10% deposit: ~€38,669\n\n  At-Home Student (balance: €6,750, saves: €265/mo, potential: €675/mo):\n    Without app                → NOT reached within 10 years\n    Conservative (45%)         → NOT reached within 10 years\n    Base (60%)                 → NOT reached within 10 years\n    Optimistic (80%)           → deposit in 113 months (9.4 years)\n\n  Full-Time Worker (balance: €3,050, saves: €510/mo, potential: €1,500/mo):\n    Without app                → NOT reached within 10 years\n    Conservative (45%)         → deposit in  86 months (7.2 years)\n    Base (60%)                 → deposit in  56 months (4.7 years)\n    Optimistic (80%)           → deposit in  38 months (3.2 years)\n\n```\n:::\n:::\n\n\n### Section 9 — Interpretation & Conclusion\n\n**The StepStone value proposition, backed by data:**\n\nOur analysis brings together three independent pieces of evidence to build the business case:\n\n1. **Regression 1** (Section 6): Students living at home have **€381 higher saving potential** per month than renters (controlling for other factors), driven by dramatically lower essential spending. Employment status is the strongest driver overall, with full-time workers gaining +€2,098 and part-time workers +€617 compared to unemployed students.\n\n2. **Regression 2** (Section 7): Despite higher saving potential, at-home students spend **€43 more per month on discretionary items** than renters, and full-time employed students spend **€163 more**, even after controlling for budget size. This is a behavioural overspend — money that could be saved but is consumed on non-essentials.\n\n3. **Time Series Forecast** (Section 8): Irish house prices are projected to continue rising over the next decade (ARIMA(2,2,4), dynamic MAPE = 1.93%). The deposit target is a moving goalpost — the longer a student waits, the more they need.\n\n**The conversion rate problem:** Across our dataset, students convert only ~21% of their saving potential into actual savings. The remaining ~79% is consumed by discretionary spending. StepStone's core mechanism is to improve this conversion rate through spending awareness and automated savings nudges.\n\n**Three app scenarios** illustrate the impact of different adoption levels:\n\n- **Conservative (45%)** — a modest improvement, roughly doubling the current rate.\n- **Base (60%)** — the target scenario, tripling the current rate. Represents a student who actively engages with StepStone's budgeting tools and savings goals.\n- **Optimistic (80%)** — an ambitious but achievable target for highly motivated savers who treat homeownership as a priority.\n\n**Results:** The rising deposit line shows that saving at the current rate (~21%) is not sufficient to reach it in foreseeable future. The app scenarios demonstrate that even a moderate improvement in saving behaviour (45%) can dramatically accelerate the path to homeownership.\n\n**Assumptions & Limitations:**\n\n- Income and spending are held constant over the projection — in reality, students graduate and earn more, which would accelerate savings (making this projection conservative). Moreover, healthy financial habits developed during student years tend to persist into adulthood, meaning the behavioural change the app fosters early on can compound into even greater savings as incomes rise.\n- No interest or returns on accumulated savings are modelled — a real savings account would compound, further improving the outlook\n- Inflation is not accounted for — this would cause increase in essential spending -> decrease in savings potential\n- We assume both selected students want to buy a house as soon as possible\n- We do not consider the income levels required to qualify for a mortgage — only the deposit requirement\n- We assume a 90% LTV ratio (10% deposit), per Central Bank of Ireland rules for first-time buyers; in practice, LTV requirements can vary\n- The two students shown are randomly selected and may not be representative of all students\n- The savings analysis is based on cross-sectional survey data, not longitudinal tracking\n- The ARIMA forecast assumes past price trends continue — it cannot predict structural shocks (e.g. policy changes, economic crises)\n- The app conversion rates (45%/60%/80%) are scenario targets — individual responses to behavioural nudges will vary\n\n",
    "supporting": [
      "econometrics-project_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}