project:
  type: website
  output-dir: docs

website:
  title: "Daniel Vala"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: achievements.qmd
        text: Achievements
      - href: projects/index.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
    right:
      - icon: file-earmark-pdf
        href: assets/cv.pdf
        text: CV
      - icon: github
        href: https://github.com/DangerX347/DangerX347.github.io
  page-footer:
    center: "Copyright 2025 Daniel Vala. All rights reserved."
  search: true

format:
  html:
    theme:
      light:
        - cosmo
        - styles.scss
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    code-copy: true
    anchor-sections: true
    smooth-scroll: true
    mainfont: "Inter"

execute:
  freeze: auto
