project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    pinned: true
    logo: assets/images/logo.png
    left:
      - href: "index.qmd#about-me"
        text: "![](/assets/images/icon-about.png){.nav-icon} About Me"
      - href: "index.qmd#achievements"
        text: "![](/assets/images/icon-achievements.png){.nav-icon} Achievements"
      - href: "index.qmd#projects"
        text: "![](/assets/images/icon-projects.png){.nav-icon} Projects"
      - href: "index.qmd#hobbies"
        text: "![](/assets/images/icon-hobbies.png){.nav-icon} Hobbies"
      - href: "index.qmd#contact"
        text: "![](/assets/images/icon-contact.png){.nav-icon} Contact"
    right:
      - icon: file-earmark-pdf
        href: assets/cv.pdf
        text: CV
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-vala-0a6b132b9
      - icon: envelope
        href: mailto:daniel.vala2@mail.dcu.ie
      - icon: github
        href: https://github.com/DangerX347/DangerX347.github.io
  page-footer:
    center: "Copyright 2025 Daniel Vala. All rights reserved."
  search: true

format:
  html:
    theme:
      light:
        - cosmo
        - styles.scss
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    code-copy: true
    anchor-sections: true
    smooth-scroll: true
    mainfont: "Inter"
    include-after-body: scrollspy.html

execute:
  freeze: auto
